package addriddles

import (
	"gorm.io/gorm"

	"Riddle_ToD/Serverside/database"
)

func Addriddle(db *gorm.DB) {

	riddles := []database.Riddle{
		{
			ID:         1,
			Question:   "What has to be broken before you can use it?",
			Answer:     "An egg",
			Category:   "Logic",
			Difficulty: "Easy",
			Points:     5,
			Choices: []database.Choice{
				{ID: 1, RiddleID: 1, Text: "A coconut"},
				{ID: 2, RiddleID: 1, Text: "An egg"},
				{ID: 3, RiddleID: 1, Text: "A glass bottle"},
				{ID: 4, RiddleID: 1, Text: "A lock"},
			},
			Hints: []database.Hint{
				{ID: 1, RiddleID: 1, Text: "It’s often part of breakfast."},
				{ID: 2, RiddleID: 1, Text: "It has a shell."},
			},
		},
		{
			ID:         2,
			Question:   "I’m tall when I’m young, and I’m short when I’m old. What am I?",
			Answer:     "A candle",
			Category:   "Logic",
			Difficulty: "Easy",
			Points:     5,
			Choices: []database.Choice{
				{ID: 5, RiddleID: 2, Text: "A candle"},
				{ID: 6, RiddleID: 2, Text: "A pencil"},
				{ID: 7, RiddleID: 2, Text: "A tree"},
				{ID: 8, RiddleID: 2, Text: "A shadow"},
			},
			Hints: []database.Hint{
				{ID: 3, RiddleID: 2, Text: "It gives light."},
				{ID: 4, RiddleID: 2, Text: "It melts as it’s used."},
			},
		},
		{
			ID:         3,
			Question:   "What has a heart that doesn’t beat?",
			Answer:     "An artichoke",
			Category:   "General",
			Difficulty: "Medium",
			Points:     10,
			Choices: []database.Choice{
				{ID: 9, RiddleID: 3, Text: "An artichoke"},
				{ID: 10, RiddleID: 3, Text: "A clock"},
				{ID: 11, RiddleID: 3, Text: "A stone"},
				{ID: 12, RiddleID: 3, Text: "A statue"},
			},
			Hints: []database.Hint{
				{ID: 5, RiddleID: 3, Text: "It’s a type of vegetable."},
				{ID: 6, RiddleID: 3, Text: "It’s often eaten in salads or dips."},
			},
		},
		{
			ID:         4,
			Question:   "I’m tall when I’m young, and I’m short when I’m old. What am I?",
			Answer:     "A candle",
			Category:   "Logic",
			Difficulty: "Easy",
			Points:     5,
			Choices: []database.Choice{
				{ID: 13, RiddleID: 4, Text: "A tree"},
				{ID: 14, RiddleID: 4, Text: "A candle"},
				{ID: 15, RiddleID: 4, Text: "A pencil"},
				{ID: 16, RiddleID: 4, Text: "A shadow"},
			},
			Hints: []database.Hint{
				{ID: 7, RiddleID: 4, Text: "It is made of wax."},
				{ID: 8, RiddleID: 4, Text: "It gives light."},
			},
		},
		{
			ID:         5,
			Question:   "What has a heart that doesn’t beat?",
			Answer:     "An artichoke",
			Category:   "General",
			Difficulty: "Medium",
			Points:     10,
			Choices: []database.Choice{
				{ID: 17, RiddleID: 5, Text: "A robot"},
				{ID: 18, RiddleID: 5, Text: "An artichoke"},
				{ID: 19, RiddleID: 5, Text: "A clock"},
				{ID: 20, RiddleID: 5, Text: "A stone"},
			},
			Hints: []database.Hint{
				{ID: 9, RiddleID: 5, Text: "It is a vegetable."},
				{ID: 10, RiddleID: 5, Text: "You eat its leaves."},
			},
		},
		{
			ID:         6,
			Question:   "What has keys but can’t open locks?",
			Answer:     "A piano",
			Category:   "General",
			Difficulty: "Easy",
			Points:     5,
			Choices: []database.Choice{
				{ID: 21, RiddleID: 6, Text: "A keyboard"},
				{ID: 22, RiddleID: 6, Text: "A piano"},
				{ID: 23, RiddleID: 6, Text: "A lockbox"},
				{ID: 24, RiddleID: 6, Text: "A treasure chest"},
			},
			Hints: []database.Hint{
				{ID: 11, RiddleID: 6, Text: "It makes music."},
				{ID: 12, RiddleID: 6, Text: "It has black and white keys."},
			},
		},
		{
			ID:         7,
			Question:   "The more you take, the more you leave behind. What am I?",
			Answer:     "Footsteps",
			Category:   "Logic",
			Difficulty: "Medium",
			Points:     10,
			Choices: []database.Choice{
				{ID: 25, RiddleID: 7, Text: "Sand"},
				{ID: 26, RiddleID: 7, Text: "Footsteps"},
				{ID: 27, RiddleID: 7, Text: "Time"},
				{ID: 28, RiddleID: 7, Text: "Shadows"},
			},
			Hints: []database.Hint{
				{ID: 13, RiddleID: 7, Text: "It’s related to walking."},
				{ID: 14, RiddleID: 7, Text: "It is left on the ground."},
			},
		},
		{
			ID:         8,
			Question:   "What has a face and two hands but no arms or legs?",
			Answer:     "A clock",
			Category:   "General",
			Difficulty: "Easy",
			Points:     5,
			Choices: []database.Choice{
				{ID: 29, RiddleID: 8, Text: "A clock"},
				{ID: 30, RiddleID: 8, Text: "A robot"},
				{ID: 31, RiddleID: 8, Text: "A compass"},
				{ID: 32, RiddleID: 8, Text: "A doll"},
			},
			Hints: []database.Hint{
				{ID: 15, RiddleID: 8, Text: "It tells time."},
				{ID: 16, RiddleID: 8, Text: "It’s found on walls or wrists."},
			},
		},
		{
			ID:         9,
			Question:   "I’m light as a feather, yet the strongest person can’t hold me for more than a minute. What am I?",
			Answer:     "Your breath",
			Category:   "Logic",
			Difficulty: "Medium",
			Points:     10,
			Choices: []database.Choice{
				{ID: 33, RiddleID: 9, Text: "A balloon"},
				{ID: 34, RiddleID: 9, Text: "Your breath"},
				{ID: 35, RiddleID: 9, Text: "A thought"},
				{ID: 36, RiddleID: 9, Text: "A cloud"},
			},
			Hints: []database.Hint{
				{ID: 17, RiddleID: 9, Text: "It’s part of your body."},
				{ID: 18, RiddleID: 9, Text: "You need it to survive."},
			},
		},
		{
			ID:         10,
			Question:   "I’m always on my way but never arrive. What am I?",
			Answer:     "Tomorrow",
			Category:   "Logic",
			Difficulty: "Hard",
			Points:     15,
			Choices: []database.Choice{
				{ID: 37, RiddleID: 10, Text: "A train"},
				{ID: 38, RiddleID: 10, Text: "Tomorrow"},
				{ID: 39, RiddleID: 10, Text: "The future"},
				{ID: 40, RiddleID: 10, Text: "A comet"},
			},
			Hints: []database.Hint{
				{ID: 19, RiddleID: 10, Text: "It’s part of time."},
				{ID: 20, RiddleID: 10, Text: "It never arrives today."},
			},
		},
		{
			ID:         11,
			Question:   "What gets wetter the more it dries?",
			Answer:     "A towel",
			Category:   "Logic",
			Difficulty: "Easy",
			Points:     5,
			Choices: []database.Choice{
				{ID: 41, RiddleID: 11, Text: "A sponge"},
				{ID: 42, RiddleID: 11, Text: "A towel"},
				{ID: 43, RiddleID: 11, Text: "Rain"},
				{ID: 44, RiddleID: 11, Text: "A cloud"},
			},
			Hints: []database.Hint{
				{ID: 21, RiddleID: 11, Text: "You use it after a shower."},
				{ID: 22, RiddleID: 11, Text: "It absorbs water."},
			},
		},
		{
			ID:         12,
			Question:   "What has a head, a tail, is brown, and has no legs?",
			Answer:     "A penny",
			Category:   "General",
			Difficulty: "Easy",
			Points:     5,
			Choices: []database.Choice{
				{ID: 45, RiddleID: 12, Text: "A coin"},
				{ID: 46, RiddleID: 12, Text: "A penny"},
				{ID: 47, RiddleID: 12, Text: "A snake"},
				{ID: 48, RiddleID: 12, Text: "A worm"},
			},
			Hints: []database.Hint{
				{ID: 23, RiddleID: 12, Text: "It is money."},
				{ID: 24, RiddleID: 12, Text: "It’s often copper-colored."},
			},
		},
		{
			ID:         13,
			Question:   "What comes once in a minute, twice in a moment, but never in a thousand years?",
			Answer:     "The letter M",
			Category:   "Word",
			Difficulty: "Medium",
			Points:     10,
			Choices: []database.Choice{
				{ID: 49, RiddleID: 13, Text: "The letter M"},
				{ID: 50, RiddleID: 13, Text: "Time"},
				{ID: 51, RiddleID: 13, Text: "A second"},
				{ID: 52, RiddleID: 13, Text: "Infinity"},
			},
			Hints: []database.Hint{
				{ID: 25, RiddleID: 13, Text: "It’s part of a word."},
				{ID: 26, RiddleID: 13, Text: "It’s a letter in the alphabet."},
			},
		},
		{
			ID:         14,
			Question:   "I have branches, but no fruit, trunk, or leaves. What am I?",
			Answer:     "A bank",
			Category:   "Logic",
			Difficulty: "Medium",
			Points:     10,
			Choices: []database.Choice{
				{ID: 53, RiddleID: 14, Text: "A river"},
				{ID: 54, RiddleID: 14, Text: "A bank"},
				{ID: 55, RiddleID: 14, Text: "A tree"},
				{ID: 56, RiddleID: 14, Text: "A map"},
			},
			Hints: []database.Hint{
				{ID: 27, RiddleID: 14, Text: "It involves money."},
				{ID: 28, RiddleID: 14, Text: "It has physical locations."},
			},
		},
		{
			ID:         15,
			Question:   "The more you take away from me, the bigger I get. What am I?",
			Answer:     "A hole",
			Category:   "Logic",
			Difficulty: "Medium",
			Points:     10,
			Choices: []database.Choice{
				{ID: 57, RiddleID: 15, Text: "A hole"},
				{ID: 58, RiddleID: 15, Text: "A crater"},
				{ID: 59, RiddleID: 15, Text: "A shadow"},
				{ID: 60, RiddleID: 15, Text: "A vacuum"},
			},
			Hints: []database.Hint{
				{ID: 29, RiddleID: 15, Text: "It’s an empty space."},
				{ID: 30, RiddleID: 15, Text: "You dig it to make it bigger."},
			},
		},
		{
			ID:         16,
			Question:   "What has an eye but cannot see?",
			Answer:     "A needle",
			Category:   "General",
			Difficulty: "Easy",
			Points:     5,
			Choices: []database.Choice{
				{ID: 61, RiddleID: 16, Text: "A needle"},
				{ID: 62, RiddleID: 16, Text: "A storm"},
				{ID: 63, RiddleID: 16, Text: "A potato"},
				{ID: 64, RiddleID: 16, Text: "A blindfold"},
			},
			Hints: []database.Hint{
				{ID: 31, RiddleID: 16, Text: "It’s used in sewing."},
				{ID: 32, RiddleID: 16, Text: "Thread passes through it."},
			},
		},
		{
			ID:         17,
			Question:   "I’m not alive, but I can grow. I don’t have lungs, but I need air. What am I?",
			Answer:     "Fire",
			Category:   "Logic",
			Difficulty: "Medium",
			Points:     10,
			Choices: []database.Choice{
				{ID: 65, RiddleID: 17, Text: "Fire"},
				{ID: 66, RiddleID: 17, Text: "A plant"},
				{ID: 67, RiddleID: 17, Text: "A balloon"},
				{ID: 68, RiddleID: 17, Text: "A shadow"},
			},
			Hints: []database.Hint{
				{ID: 33, RiddleID: 17, Text: "It’s hot and bright."},
				{ID: 34, RiddleID: 17, Text: "It consumes fuel to exist."},
			},
		},
		{
			ID:         18,
			Question:   "The more you have of me, the less you see. What am I?",
			Answer:     "Darkness",
			Category:   "Logic",
			Difficulty: "Medium",
			Points:     10,
			Choices: []database.Choice{
				{ID: 69, RiddleID: 18, Text: "Fog"},
				{ID: 70, RiddleID: 18, Text: "Darkness"},
				{ID: 71, RiddleID: 18, Text: "A blindfold"},
				{ID: 72, RiddleID: 18, Text: "A shadow"},
			},
			Hints: []database.Hint{
				{ID: 35, RiddleID: 18, Text: "It happens at night."},
				{ID: 36, RiddleID: 18, Text: "It’s the absence of light."},
			},
		},
		{
			ID:         19,
			Question:   "What has a neck but no head?",
			Answer:     "A bottle",
			Category:   "General",
			Difficulty: "Easy",
			Points:     5,
			Choices: []database.Choice{
				{ID: 73, RiddleID: 19, Text: "A bottle"},
				{ID: 74, RiddleID: 19, Text: "A shirt"},
				{ID: 75, RiddleID: 19, Text: "A vase"},
				{ID: 76, RiddleID: 19, Text: "A guitar"},
			},
			Hints: []database.Hint{
				{ID: 37, RiddleID: 19, Text: "It holds liquids."},
				{ID: 38, RiddleID: 19, Text: "It’s made of glass or plastic."},
			},
		},
		{
			ID:         20,
			Question:   "I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. What am I?",
			Answer:     "An echo",
			Category:   "Logic",
			Difficulty: "Hard",
			Points:     15,
			Choices: []database.Choice{
				{ID: 77, RiddleID: 20, Text: "An echo"},
				{ID: 78, RiddleID: 20, Text: "A ghost"},
				{ID: 79, RiddleID: 20, Text: "The wind"},
				{ID: 80, RiddleID: 20, Text: "A shadow"},
			},
			Hints: []database.Hint{
				{ID: 39, RiddleID: 20, Text: "It’s a sound."},
				{ID: 40, RiddleID: 20, Text: "It repeats what you say."},
			},
		},
		{
			ID:         21,
			Question:   "How do you go from 98 to 720 using just one letter?",
			Answer:     "Add 'X' to '98' to make it 9X8, which equals 720.",
			Category:   "Mathematics",
			Difficulty: "Hard",
			Points:     15,
			Choices: []database.Choice{
				{ID: 1, RiddleID: 1, Text: "Add X"},
				{ID: 2, RiddleID: 1, Text: "Add V"},
				{ID: 3, RiddleID: 1, Text: "Add L"},
				{ID: 4, RiddleID: 1, Text: "Add I"},
			},
			Hints: []database.Hint{
				{ID: 1, RiddleID: 1, Text: "Think Roman numerals."},
				{ID: 2, RiddleID: 1, Text: "X represents multiplication."},
			},
		},
		{
			ID:         22,
			Question:   "A merchant can place 8 large boxes or 10 small boxes into a carton for shipping. In one shipment, he sent a total of 96 boxes. How many cartons did he ship if there are more large boxes than small boxes?",
			Answer:     "11 cartons (8 large boxes and 3 small boxes).",
			Category:   "Mathematics",
			Difficulty: "Medium",
			Points:     10,
			Choices: []database.Choice{
				{ID: 5, RiddleID: 2, Text: "9"},
				{ID: 6, RiddleID: 2, Text: "11"},
				{ID: 7, RiddleID: 2, Text: "10"},
				{ID: 8, RiddleID: 2, Text: "12"},
			},
			Hints: []database.Hint{
				{ID: 3, RiddleID: 2, Text: "Use equations to balance large and small boxes."},
				{ID: 4, RiddleID: 2, Text: "Focus on multiples of 8 and 10."},
			},
		},
		{
			ID:         23,
			Question:   "Can you write down eight eights so that they add up to one thousand?",
			Answer:     "888 + 88 + 8 + 8 + 8 = 1000.",
			Category:   "Mathematics",
			Difficulty: "Easy",
			Points:     5,
			Choices: []database.Choice{
				{ID: 9, RiddleID: 3, Text: "888 + 88 + 8 + 8 + 8"},
				{ID: 10, RiddleID: 3, Text: "888 + 88 + 8 + 16"},
				{ID: 11, RiddleID: 3, Text: "888 + 88 + 4 + 20"},
				{ID: 12, RiddleID: 3, Text: "None of the above"},
			},
			Hints: []database.Hint{
				{ID: 5, RiddleID: 3, Text: "Use mathematical addition with digits 8."},
				{ID: 6, RiddleID: 3, Text: "Think about the placement of digits."},
			},
		},
		{
			ID:         24,
			Question:   "A couple went for a picnic. They have 5 sons and each son has three sisters. Each sister has one baby. In total how many people went for the picnic?",
			Answer:     "The couple, 5 sons, 3 sisters, and 3 babies = 13 people.",
			Category:   "Mathematics",
			Difficulty: "Medium",
			Points:     10,
			Choices: []database.Choice{
				{ID: 13, RiddleID: 4, Text: "11"},
				{ID: 14, RiddleID: 4, Text: "13"},
				{ID: 15, RiddleID: 4, Text: "12"},
				{ID: 16, RiddleID: 4, Text: "14"},
			},
			Hints: []database.Hint{
				{ID: 7, RiddleID: 4, Text: "Count all the family members, including babies."},
				{ID: 8, RiddleID: 4, Text: "Be careful not to double count."},
			},
		},
		{
			ID:         25,
			Question:   "What number do you get when you multiply all the numbers of a telephone dialpad?",
			Answer:     "0 (because the dialpad contains 0, and any number multiplied by 0 is 0).",
			Category:   "Mathematics",
			Difficulty: "Easy",
			Points:     5,
			Choices: []database.Choice{
				{ID: 17, RiddleID: 5, Text: "0"},
				{ID: 18, RiddleID: 5, Text: "1"},
				{ID: 19, RiddleID: 5, Text: "9"},
				{ID: 20, RiddleID: 5, Text: "None of the above"},
			},
			Hints: []database.Hint{
				{ID: 9, RiddleID: 5, Text: "Think about what happens when you multiply by 0."},
			},
		},
		{
			ID:         26,
			Question:   "What is the next number in the sequence 2, 3, 5, 8, 13?",
			Answer:     "21 (each number is the sum of the two preceding numbers).",
			Category:   "Mathematics",
			Difficulty: "Medium",
			Points:     10,
			Choices: []database.Choice{
				{ID: 21, RiddleID: 6, Text: "19"},
				{ID: 22, RiddleID: 6, Text: "20"},
				{ID: 23, RiddleID: 6, Text: "21"},
				{ID: 24, RiddleID: 6, Text: "22"},
			},
			Hints: []database.Hint{
				{ID: 10, RiddleID: 6, Text: "Observe how each number is related to the previous ones."},
			},
		},
		{
			ID:         27,
			Question:   "There are seven people at a party. They meet each other and each of them shakes hands only once with each of the others. How many handshakes will there be in total?",
			Answer:     "21 (calculated using the formula n(n-1)/2, where n = 7).",
			Category:   "Mathematics",
			Difficulty: "Medium",
			Points:     10,
			Choices: []database.Choice{
				{ID: 25, RiddleID: 7, Text: "19"},
				{ID: 26, RiddleID: 7, Text: "21"},
				{ID: 27, RiddleID: 7, Text: "28"},
				{ID: 28, RiddleID: 7, Text: "35"},
			},
			Hints: []database.Hint{
				{ID: 11, RiddleID: 7, Text: "Each handshake involves a pair of people."},
				{ID: 12, RiddleID: 7, Text: "Use the formula n(n-1)/2."},
			},
		},
		{
			ID:         28,
			Question:   "What is 7 + 7 ÷ 7 + 7 x 7 - 7?",
			Answer:     "50 (following the order of operations: BODMAS).",
			Category:   "Mathematics",
			Difficulty: "Easy",
			Points:     5,
			Choices: []database.Choice{
				{ID: 29, RiddleID: 8, Text: "48"},
				{ID: 30, RiddleID: 8, Text: "49"},
				{ID: 31, RiddleID: 8, Text: "50"},
				{ID: 32, RiddleID: 8, Text: "51"},
			},
			Hints: []database.Hint{
				{ID: 13, RiddleID: 8, Text: "Follow BODMAS rules (parentheses, orders, division/multiplication, addition/subtraction)."},
			},
		},
		{
			ID:         29,
			Question:   "If there are four apples and you take away three of them, how many apples do you have?",
			Answer:     "3 (because you took away three).",
			Category:   "Mathematics",
			Difficulty: "Easy",
			Points:     5,
			Choices: []database.Choice{
				{ID: 33, RiddleID: 9, Text: "1"},
				{ID: 34, RiddleID: 9, Text: "3"},
				{ID: 35, RiddleID: 9, Text: "4"},
				{ID: 36, RiddleID: 9, Text: "None of the above"},
			},
			Hints: []database.Hint{
				{ID: 14, RiddleID: 9, Text: "Focus on how many you take away."},
			},
		},
		{
			ID:         30,
			Question:   "A father and his son's ages add up to 66. The father's age is the reverse of his son's age. How old are they?",
			Answer:     "51 and 15, 42 and 24, or 60 and 06.",
			Category:   "Logic",
			Difficulty: "Mathematics",
			Points:     15,
			Choices: []database.Choice{
				{ID: 37, RiddleID: 10, Text: "51 and 15"},
				{ID: 38, RiddleID: 10, Text: "42 and 24"},
				{ID: 39, RiddleID: 10, Text: "60 and 06"},
				{ID: 40, RiddleID: 10, Text: "All of the above"},
			},
			Hints: []database.Hint{
				{ID: 15, RiddleID: 10, Text: "Consider reversing the digits of two numbers that add up to 66."},
			},
		},
		{
			ID:         31,
			Question:   "I am a three-digit number. My second digit is four times bigger than the third digit, and my first digit is three less than the second digit. What number am I?",
			Answer:     "141",
			Category:   "Mathematics",
			Difficulty: "Medium",
			Points:     10,
			Choices: []database.Choice{
				{ID: 41, RiddleID: 11, Text: "123"},
				{ID: 42, RiddleID: 11, Text: "141"},
				{ID: 43, RiddleID: 11, Text: "142"},
				{ID: 44, RiddleID: 11, Text: "None of the above"},
			},
			Hints: []database.Hint{
				{ID: 16, RiddleID: 11, Text: "The digits follow a specific mathematical relationship."},
			},
		},
		{
			ID:         32,
			Question:   "How many times can you subtract five from twenty-five?",
			Answer:     "Once (after the first subtraction, it’s no longer 25).",
			Category:   "Mathematics",
			Difficulty: "Easy",
			Points:     5,
			Choices: []database.Choice{
				{ID: 45, RiddleID: 12, Text: "1"},
				{ID: 46, RiddleID: 12, Text: "5"},
				{ID: 47, RiddleID: 12, Text: "25"},
				{ID: 48, RiddleID: 12, Text: "None of the above"},
			},
			Hints: []database.Hint{
				{ID: 17, RiddleID: 12, Text: "Think about what happens after the first subtraction."},
			},
		},
		{
			ID:         33,
			Question:   "I add five to nine and get two as the answer. The answer is accurate. How?",
			Answer:     "It’s using a clock (9 + 5 = 2 on a clock).",
			Category:   "Mathematics",
			Difficulty: "Medium",
			Points:     10,
			Choices: []database.Choice{
				{ID: 49, RiddleID: 13, Text: "Clock arithmetic"},
				{ID: 50, RiddleID: 13, Text: "Incorrect math"},
				{ID: 51, RiddleID: 13, Text: "Binary addition"},
				{ID: 52, RiddleID: 13, Text: "None of the above"},
			},
			Hints: []database.Hint{
				{ID: 18, RiddleID: 13, Text: "Consider time instead of standard math."},
			},
		},
		{
			ID:         34,
			Question:   "Two fathers and two sons went fishing one day. At the end of the day, each of them had one fish. There were three fish in total. How is it possible?",
			Answer:     "It’s a grandfather, father, and son (3 people total).",
			Category:   "Mathematics",
			Difficulty: "Easy",
			Points:     5,
			Choices: []database.Choice{
				{ID: 53, RiddleID: 14, Text: "3 people: grandfather, father, son"},
				{ID: 54, RiddleID: 14, Text: "4 people with shared fish"},
				{ID: 55, RiddleID: 14, Text: "3 people with extra fish"},
				{ID: 56, RiddleID: 14, Text: "None of the above"},
			},
			Hints: []database.Hint{
				{ID: 19, RiddleID: 14, Text: "One person can be both a father and a son."},
			},
		},
		{
			ID:         35,
			Question:   "If 7 is transformed into 13 and 11 into 21, what does 16 become?",
			Answer:     "31 (add 6 to the number and double the result).",
			Category:   "Mathematics",
			Difficulty: "Medium",
			Points:     10,
			Choices: []database.Choice{
				{ID: 57, RiddleID: 15, Text: "31"},
				{ID: 58, RiddleID: 15, Text: "32"},
				{ID: 59, RiddleID: 15, Text: "33"},
				{ID: 60, RiddleID: 15, Text: "None of the above"},
			},
			Hints: []database.Hint{
				{ID: 20, RiddleID: 15, Text: "Add 6, then double."},
			},
		},
		{
			ID:         36,
			Question:   "I am a number, but when you add 'G' to me, I go away. What number am I?",
			Answer:     "0 (add 'G' to make it 'GONE').",
			Category:   "Mathematics",
			Difficulty: "Easy",
			Points:     5,
			Choices: []database.Choice{
				{ID: 61, RiddleID: 16, Text: "0"},
				{ID: 62, RiddleID: 16, Text: "1"},
				{ID: 63, RiddleID: 16, Text: "10"},
				{ID: 64, RiddleID: 16, Text: "None of the above"},
			},
			Hints: []database.Hint{
				{ID: 21, RiddleID: 16, Text: "Think about the word 'GONE'."},
			},
		},
		{
			ID:         37,
			Question:   "What can you put between 7 and 8 to get a result bigger than 7, but not quite as high as 8?",
			Answer:     "A decimal point (7.8).",
			Category:   "Mathematics",
			Difficulty: "Easy",
			Points:     5,
			Choices: []database.Choice{
				{ID: 65, RiddleID: 17, Text: "A decimal point"},
				{ID: 66, RiddleID: 17, Text: "A plus sign"},
				{ID: 67, RiddleID: 17, Text: "A fraction"},
				{ID: 68, RiddleID: 17, Text: "None of the above"},
			},
			Hints: []database.Hint{
				{ID: 22, RiddleID: 17, Text: "What happens when you add a decimal point?"},
			},
		},
		{
			ID:         38,
			Question:   "Turn me on my side and I am everything. Cut me in half and I am nothing. What am I?",
			Answer:     "The number 8.",
			Category:   "Mathematics",
			Difficulty: "Medium",
			Points:     10,
			Choices: []database.Choice{
				{ID: 69, RiddleID: 18, Text: "8"},
				{ID: 70, RiddleID: 18, Text: "0"},
				{ID: 71, RiddleID: 18, Text: "∞"},
				{ID: 72, RiddleID: 18, Text: "None of the above"},
			},
			Hints: []database.Hint{
				{ID: 23, RiddleID: 18, Text: "What number resembles infinity on its side?"},
			},
		},
		{
			ID:         39,
			Question:   "I am four times as old as my daughter. 20 years from now, I will be twice as old as her. How old are we now?",
			Answer:     "The daughter is 10 years old, and the parent is 40.",
			Category:   "Mathematics",
			Difficulty: "Medium",
			Points:     10,
			Choices: []database.Choice{
				{ID: 73, RiddleID: 19, Text: "Daughter: 10, Parent: 40"},
				{ID: 74, RiddleID: 19, Text: "Daughter: 15, Parent: 60"},
				{ID: 75, RiddleID: 19, Text: "Daughter: 20, Parent: 80"},
				{ID: 76, RiddleID: 19, Text: "None of the above"},
			},
			Hints: []database.Hint{
				{ID: 24, RiddleID: 19, Text: "Set up a system of equations for their ages."},
			},
		},
		{
			ID:         40,
			Question:   "You are running a race with a group of people and pass the person in second place. What place would you be in now?",
			Answer:     "Second place.",
			Category:   "Mathematics",
			Difficulty: "Easy",
			Points:     5,
			Choices: []database.Choice{
				{ID: 77, RiddleID: 20, Text: "First place"},
				{ID: 78, RiddleID: 20, Text: "Second place"},
				{ID: 79, RiddleID: 20, Text: "Third place"},
				{ID: 80, RiddleID: 20, Text: "None of the above"},
			},
			Hints: []database.Hint{
				{ID: 25, RiddleID: 20, Text: "What happens when you pass the second-place person?"},
			},
		},
		{
			ID:         41,
			Question:   "If Reema is the 50th fastest and 50th slowest runner in her school. How many students are there in the school?",
			Answer:     "99 (she is exactly in the middle).",
			Category:   "Mathematics",
			Difficulty: "Easy",
			Points:     5,
			Choices: []database.Choice{
				{ID: 81, RiddleID: 21, Text: "99"},
				{ID: 82, RiddleID: 21, Text: "100"},
				{ID: 83, RiddleID: 21, Text: "50"},
				{ID: 84, RiddleID: 21, Text: "None of the above"},
			},
			Hints: []database.Hint{
				{ID: 26, RiddleID: 21, Text: "How many students are there if she's exactly in the middle?"},
			},
		},
		{
			ID:         42,
			Question:   "Three times what number is not larger than two times the same number?",
			Answer:     "0 (0 is the only number where this condition holds true).",
			Category:   "Mathematics",
			Difficulty: "Easy",
			Points:     5,
			Choices: []database.Choice{
				{ID: 85, RiddleID: 22, Text: "0"},
				{ID: 86, RiddleID: 22, Text: "1"},
				{ID: 87, RiddleID: 22, Text: "2"},
				{ID: 88, RiddleID: 22, Text: "None of the above"},
			},
			Hints: []database.Hint{
				{ID: 27, RiddleID: 22, Text: "What happens when you multiply zero?"},
			},
		},
		{
			ID:         43,
			Question:   "The head of a bird is 9 cm long. Its tail is equal to the size of its head plus half the size of its body. Also, its body is equal to the size of its head plus its tail. The length of the bird will be?",
			Answer:     "72 cm.",
			Category:   "Math",
			Difficulty: "Hard",
			Points:     15,
			Choices: []database.Choice{
				{ID: 89, RiddleID: 23, Text: "72 cm"},
				{ID: 90, RiddleID: 23, Text: "60 cm"},
				{ID: 91, RiddleID: 23, Text: "81 cm"},
				{ID: 92, RiddleID: 23, Text: "None of the above"},
			},
			Hints: []database.Hint{
				{ID: 28, RiddleID: 23, Text: "Use equations to represent the head, tail, and body sizes."},
			},
		},
		{
			ID:         44,
			Question:   "What three positive numbers after addition and multiplication give the same result?",
			Answer:     "1, 2, and 3.",
			Category:   "Mathematics",
			Difficulty: "Medium",
			Points:     10,
			Choices: []database.Choice{
				{ID: 93, RiddleID: 24, Text: "1, 2, and 3"},
				{ID: 94, RiddleID: 24, Text: "2, 3, and 4"},
				{ID: 95, RiddleID: 24, Text: "3, 4, and 5"},
				{ID: 96, RiddleID: 24, Text: "None of the above"},
			},
			Hints: []database.Hint{
				{ID: 29, RiddleID: 24, Text: "Try small integers."},
			},
		},
		{
			ID:         45,
			Question:   "A zoo has 100 pairs of dogs. Every dog gave birth to two pairs of babies. Unfortunately, 23 of the dogs did not survive. How many dogs are left in the zoo in total?",
			Answer:     "977 (each pair has 4 puppies, and 23 adults died).",
			Category:   "Mathematics",
			Difficulty: "Hard",
			Points:     15,
			Choices: []database.Choice{
				{ID: 97, RiddleID: 25, Text: "977"},
				{ID: 98, RiddleID: 25, Text: "950"},
				{ID: 99, RiddleID: 25, Text: "1000"},
				{ID: 100, RiddleID: 25, Text: "None of the above"},
			},
			Hints: []database.Hint{
				{ID: 30, RiddleID: 25, Text: "Count all adult dogs and their offspring."},
			},
		},
		{
			ID:         46,
			Question:   "The total cost of a pen and a notebook is ₹150. The pen costs ₹100 more than the notebook. How much does each item cost?",
			Answer:     "Notebook: ₹25, Pen: ₹125.",
			Category:   "Math",
			Difficulty: "Easy",
			Points:     5,
			Choices: []database.Choice{
				{ID: 101, RiddleID: 26, Text: "Notebook: ₹25, Pen: ₹125"},
				{ID: 102, RiddleID: 26, Text: "Notebook: ₹50, Pen: ₹100"},
				{ID: 103, RiddleID: 26, Text: "Notebook: ₹75, Pen: ₹150"},
				{ID: 104, RiddleID: 26, Text: "None of the above"},
			},
			Hints: []database.Hint{
				{ID: 31, RiddleID: 26, Text: "Write an equation for the total cost and solve."},
			},
		},
		{
			ID:         47,
			Question:   "Raj is twice as old as his little sister and half as old as his father. After 50 years from now, his sister will be half their father's age. What is Raj's age now?",
			Answer:     "Raj is 50 years old.",
			Category:   "Math",
			Difficulty: "Medium",
			Points:     10,
			Choices: []database.Choice{
				{ID: 105, RiddleID: 27, Text: "50"},
				{ID: 106, RiddleID: 27, Text: "25"},
				{ID: 107, RiddleID: 27, Text: "75"},
				{ID: 108, RiddleID: 27, Text: "None of the above"},
			},
			Hints: []database.Hint{
				{ID: 32, RiddleID: 27, Text: "Set up equations for their ages and solve."},
			},
		},
		{
			ID:         48,
			Question:   "Find the next number in the series 7645, 5764, 4576, ..........",
			Answer:     "6457 (shift the digits cyclically).",
			Category:   "Logic",
			Difficulty: "Mathematics",
			Points:     10,
			Choices: []database.Choice{
				{ID: 109, RiddleID: 28, Text: "6457"},
				{ID: 110, RiddleID: 28, Text: "7654"},
				{ID: 111, RiddleID: 28, Text: "4765"},
				{ID: 112, RiddleID: 28, Text: "None of the above"},
			},
			Hints: []database.Hint{
				{ID: 33, RiddleID: 28, Text: "Observe how the digits shift."},
			},
		},
		{
			ID:         49,
			Question:   "You want to boil an egg for two minutes. If there is only a three-minute timer, a four-minute timer, and a five-minute timer, how can you boil the egg for two minutes only?",
			Answer:     "Start both the 3-minute and 5-minute timers. When the 3-minute timer runs out, put the egg in and let it boil for the remaining 2 minutes of the 5-minute timer.",
			Category:   "Mathematics",
			Difficulty: "Hard",
			Points:     15,
			Choices: []database.Choice{
				{ID: 113, RiddleID: 29, Text: "Use both the 3-minute and 5-minute timers strategically."},
				{ID: 114, RiddleID: 29, Text: "Use only the 4-minute timer."},
				{ID: 115, RiddleID: 29, Text: "Boil it for 3 minutes and stop early."},
				{ID: 116, RiddleID: 29, Text: "None of the above"},
			},
			Hints: []database.Hint{
				{ID: 34, RiddleID: 29, Text: "Use the timers simultaneously to measure 2 minutes."},
			},
		},
		{
			ID:         50,
			Question:   "There are men and horses in a stable. In total, there are 22 heads and 72 feet. How many men and horses are there in the stable?",
			Answer:     "14 horses and 8 men.",
			Category:   "Mathematics",
			Difficulty: "Medium",
			Points:     10,
			Choices: []database.Choice{
				{ID: 117, RiddleID: 30, Text: "14 horses and 8 men"},
				{ID: 118, RiddleID: 30, Text: "12 horses and 10 men"},
				{ID: 119, RiddleID: 30, Text: "10 horses and 12 men"},
				{ID: 120, RiddleID: 30, Text: "None of the above"},
			},
			Hints: []database.Hint{
				{ID: 35, RiddleID: 30, Text: "Each horse has 4 feet, and each man has 2 feet."},
			},
		},
		{
			ID:         51,
			Question:   "20 + 20 + 20 = 60. Make it 60 again by using a number three times (it can't be 20).",
			Answer:     "15 + 15 + 30 = 60.",
			Category:   "Mathematics",
			Difficulty: "Easy",
			Points:     5,
			Choices: []database.Choice{
				{ID: 121, RiddleID: 31, Text: "15 + 15 + 30"},
				{ID: 122, RiddleID: 31, Text: "10 + 10 + 40"},
				{ID: 123, RiddleID: 31, Text: "25 + 25 + 10"},
				{ID: 124, RiddleID: 31, Text: "None of the above"},
			},
			Hints: []database.Hint{
				{ID: 36, RiddleID: 31, Text: "Use different numbers to add up to 60."},
			},
		},
		{
			ID:         52,
			Question:   "You are 8 feet away from a door, and with each move you take, you cover half the distance to the door. How many moves will it take to reach the door?",
			Answer:     "You will never reach the door completely, but after infinite moves, you will be arbitrarily close.",
			Category:   "Mathematics",
			Difficulty: "Hard",
			Points:     15,
			Choices: []database.Choice{
				{ID: 125, RiddleID: 32, Text: "Infinite moves"},
				{ID: 126, RiddleID: 32, Text: "8 moves"},
				{ID: 127, RiddleID: 32, Text: "4 moves"},
				{ID: 128, RiddleID: 32, Text: "None of the above"},
			},
			Hints: []database.Hint{
				{ID: 37, RiddleID: 32, Text: "Each move covers only half the remaining distance."},
			},
		},
		{
			ID:         53,
			Question:   "What is the four-digit number in which the first digit is one-fourth of the last digit? The second digit is 6 times the first digit, and the third digit is the second digit plus 3.",
			Answer:     "1694.",
			Category:   "Mathematics",
			Difficulty: "Medium",
			Points:     10,
			Choices: []database.Choice{
				{ID: 129, RiddleID: 33, Text: "1694"},
				{ID: 130, RiddleID: 33, Text: "1849"},
				{ID: 131, RiddleID: 33, Text: "1468"},
				{ID: 132, RiddleID: 33, Text: "None of the above"},
			},
			Hints: []database.Hint{
				{ID: 38, RiddleID: 33, Text: "Translate the relationships into equations."},
			},
		},
		{
			ID:         54,
			Question:   "How can you get 720 by using six zeros and any mathematical operator?",
			Answer:     "720 = (0! + 0! + 0! + 0! + 0! + 0!)! (where 0! = 1).",
			Category:   "Mathematics",
			Difficulty: "Hard",
			Points:     15,
			Choices: []database.Choice{
				{ID: 133, RiddleID: 34, Text: "Use factorials of zeros."},
				{ID: 134, RiddleID: 34, Text: "Use addition only."},
				{ID: 135, RiddleID: 34, Text: "Combine multiplication and subtraction."},
				{ID: 136, RiddleID: 34, Text: "None of the above"},
			},
			Hints: []database.Hint{
				{ID: 39, RiddleID: 34, Text: "Factorials of zero are not zero."},
			},
		},
		{
			ID:         55,
			Question:   "Abir has a box of ornaments that he uses to decorate his tree on Christmas each year. All of them are blue (except for six), all of them are green (except for six), and all of them are red (except for six). How many ornaments are there of each color?",
			Answer:     "2 blue, 2 green, and 2 red ornaments.",
			Category:   "Logic",
			Difficulty: "Medium",
			Points:     10,
			Choices: []database.Choice{
				{ID: 137, RiddleID: 35, Text: "2 blue, 2 green, and 2 red"},
				{ID: 138, RiddleID: 35, Text: "3 blue, 3 green, and 3 red"},
				{ID: 139, RiddleID: 35, Text: "4 blue, 4 green, and 4 red"},
				{ID: 140, RiddleID: 35, Text: "None of the above"},
			},
			Hints: []database.Hint{
				{ID: 40, RiddleID: 35, Text: "The total of each color is always 6 minus the others."},
			},
		},
	}

}
