package addriddles

import (
	"fmt"
	"time"

	"gorm.io/gorm"

	"Riddle_ToD/Serverside/database"
)

func Addriddle(db *gorm.DB) {

	riddles := []database.Riddle{
		{
			ID:          90,
			Question:    "How many months have 28 days?",
			Answer:      "All 12 months",
			Explanation: "Every month has at least 28 days, though February is the only one with exactly 28 (in non-leap years).",
			Category:    "Logic",
			Difficulty:  "Easy",
			Points:      5,
			Choices: []database.Choice{
				{ID: 250, RiddleID: 90, Text: "One"},
				{ID: 251, RiddleID: 90, Text: "Two"},
				{ID: 252, RiddleID: 90, Text: "All 12 months"},
				{ID: 253, RiddleID: 90, Text: "February only"},
			},
			Hints: []database.Hint{
				{ID: 70, RiddleID: 90, Text: "Think about every month on the calendar."},
				{ID: 71, RiddleID: 90, Text: "Even the long months have at least 28 days."},
			},
		},
		{
			ID:          91,
			Question:    "What never asks questions but is always answered?",
			Answer:      "A Doorbell",
			Explanation: "When a doorbell rings its answered.",
			Category:    "General",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 254, RiddleID: 91, Text: "A riddle"},
				{ID: 255, RiddleID: 91, Text: "A telephone"},
				{ID: 256, RiddleID: 91, Text: "A Doorbell"},
				{ID: 257, RiddleID: 91, Text: "An echo"},
			},
			Hints: []database.Hint{
				{ID: 72, RiddleID: 91, Text: "It rings before being answered."},
			},
		},
		{
			ID:          92,
			Question:    "I am an odd number, take away a letter, I become even. What number am I?",
			Answer:      "Seven",
			Explanation: "Remove the 's' from 'seven,' and it becomes 'even.'",
			Category:    "Word",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 258, RiddleID: 92, Text: "Nine"},
				{ID: 259, RiddleID: 92, Text: "Seven"},
				{ID: 260, RiddleID: 92, Text: "Five"},
				{ID: 261, RiddleID: 92, Text: "Three"},
			},
			Hints: []database.Hint{
				{ID: 73, RiddleID: 92, Text: "It's a single-digit number."},
				{ID: 74, RiddleID: 92, Text: "Remove the first letter to find the answer."},
			},
		},
		{
			ID:          93,
			Question:    "What is easy to get into but hard to get out?",
			Answer:      "Trouble",
			Explanation: "It's common to say 'getting into trouble is easy, but getting out of it is hard.'",
			Category:    "General",
			Difficulty:  "Easy",
			Points:      5,
			Choices: []database.Choice{
				{ID: 262, RiddleID: 93, Text: "A hole"},
				{ID: 263, RiddleID: 93, Text: "Debt"},
				{ID: 264, RiddleID: 93, Text: "Trouble"},
				{ID: 265, RiddleID: 93, Text: "Quicksand"},
			},
			Hints: []database.Hint{
				{ID: 75, RiddleID: 93, Text: "It's often caused by bad decisions."},
				{ID: 76, RiddleID: 93, Text: "Kids are warned not to get into it."},
			},
		},
		{
			ID:          94,
			Question:    "What is full of holes but still holds water?",
			Answer:      "A sponge",
			Explanation: "A sponge has many holes but is designed to absorb and hold water.",
			Category:    "General",
			Difficulty:  "Easy",
			Points:      5,
			Choices: []database.Choice{
				{ID: 266, RiddleID: 94, Text: "A net"},
				{ID: 270, RiddleID: 94, Text: "A bucket"},
				{ID: 271, RiddleID: 94, Text: "A sponge"},
				{ID: 272, RiddleID: 94, Text: "A sieve"},
			},
			Hints: []database.Hint{
				{ID: 77, RiddleID: 94, Text: "You often use it for cleaning."},
				{ID: 78, RiddleID: 94, Text: "It absorbs water."},
			},
		},
		{
			ID:          95,
			Question:    "Which is heavier, a kilo of stones or a kilo of feathers?",
			Answer:      "Neither, they weigh the same",
			Explanation: "Both weigh one kilogram, so they are equal in weight.",
			Category:    "Logic",
			Difficulty:  "Easy",
			Points:      5,
			Choices: []database.Choice{
				{ID: 273, RiddleID: 95, Text: "Stones"},
				{ID: 274, RiddleID: 95, Text: "Feathers"},
				{ID: 275, RiddleID: 95, Text: "Neither, they weigh the same"},
				{ID: 276, RiddleID: 95, Text: "Depends on the density"},
			},
			Hints: []database.Hint{
				{ID: 79, RiddleID: 95, Text: "They are measured in the same unit."},
				{ID: 80, RiddleID: 95, Text: "Think about the definition of a kilogram."},
			},
		},
		{
			ID:          96,
			Question:    "What is at the end of a rainbow?",
			Answer:      "The letter W",
			Explanation: "The word 'rainbow' ends with the letter W.",
			Category:    "Word",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 277, RiddleID: 96, Text: "Gold"},
				{ID: 278, RiddleID: 96, Text: "Treasure"},
				{ID: 279, RiddleID: 96, Text: "The letter W"},
				{ID: 280, RiddleID: 96, Text: "Nothing"},
			},
			Hints: []database.Hint{
				{ID: 81, RiddleID: 96, Text: "Think about the word itself."},
				{ID: 82, RiddleID: 96, Text: "It’s not a physical object."},
			},
		},
		{
			ID:          97,
			Question:    "What three letters change a girl to a woman?",
			Answer:      "Age",
			Explanation: "As a girl grows up, age transitions her into a woman.",
			Category:    "Wordplay",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 281, RiddleID: 97, Text: "Age"},
				{ID: 282, RiddleID: 97, Text: "Her"},
				{ID: 283, RiddleID: 97, Text: "She"},
				{ID: 284, RiddleID: 97, Text: "Marriage"},
			},
			Hints: []database.Hint{
				{ID: 83, RiddleID: 97, Text: "Think about time."},
				{ID: 84, RiddleID: 97, Text: "It's related to growing older."},
			},
		},
		{
			ID:          98,
			Question:    "What can you easily break but you can never touch it?",
			Answer:      "A promise",
			Explanation: "A promise is intangible but can be broken through actions or words.",
			Category:    "General",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 285, RiddleID: 98, Text: "A glass"},
				{ID: 286, RiddleID: 98, Text: "A promise"},
				{ID: 287, RiddleID: 98, Text: "A mirror"},
				{ID: 288, RiddleID: 98, Text: "A thread"},
			},
			Hints: []database.Hint{
				{ID: 85, RiddleID: 98, Text: "It's a matter of trust."},
				{ID: 86, RiddleID: 98, Text: "You make this with words."},
			},
		},
		{
			ID:          99,
			Question:    "What question can you ask where you can get different answers every time but all the answers being correct?",
			Answer:      "What time is it?",
			Explanation: "The time changes constantly, so answers vary but remain correct.",
			Category:    "Logic",
			Difficulty:  "Easy",
			Points:      5,
			Choices: []database.Choice{
				{ID: 289, RiddleID: 99, Text: "How are you?"},
				{ID: 290, RiddleID: 99, Text: "What time is it?"},
				{ID: 291, RiddleID: 99, Text: "What is your name?"},
				{ID: 292, RiddleID: 99, Text: "What is your age?"},
			},
			Hints: []database.Hint{
				{ID: 87, RiddleID: 99, Text: "Think about something that changes constantly."},
				{ID: 88, RiddleID: 99, Text: "It's related to the clock."},
			},
		},
		{
			ID:          100,
			Question:    "I am first on earth, second in heaven. I appear twice in a week, never in a month, but once in a year. What am I?",
			Answer:      "The letter E",
			Explanation: "The letter E fits this description based on its occurrences.",
			Category:    "Word",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 293, RiddleID: 100, Text: "The letter E"},
				{ID: 294, RiddleID: 100, Text: "The moon"},
				{ID: 295, RiddleID: 100, Text: "Time"},
				{ID: 296, RiddleID: 100, Text: "Earth"},
			},
			Hints: []database.Hint{
				{ID: 89, RiddleID: 100, Text: "It's part of the alphabet."},
				{ID: 90, RiddleID: 100, Text: "It's the most commonly used letter."},
			},
		},
		{
			ID:          101,
			Question:    "What is in the beginning and the end but not in the middle?",
			Answer:      "The letter B",
			Explanation: "The word 'beginning' starts and ends with B but doesn't have it in the middle.",
			Category:    "Word",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 297, RiddleID: 101, Text: "The letter B"},
				{ID: 298, RiddleID: 101, Text: "The sun"},
				{ID: 299, RiddleID: 101, Text: "Time"},
				{ID: 300, RiddleID: 101, Text: "Nothing"},
			},
			Hints: []database.Hint{
				{ID: 91, RiddleID: 101, Text: "It's part of the word 'beginning'."},
				{ID: 92, RiddleID: 101, Text: "It's a letter."},
			},
		},
		{
			ID:          102,
			Question:    "When can you add 2 to 11 and get 1 as the answer?",
			Answer:      "On a clock",
			Explanation: "Adding 2 hours to 11 o'clock gives you 1 o'clock.",
			Category:    "Logic",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 301, RiddleID: 102, Text: "On a clock"},
				{ID: 302, RiddleID: 102, Text: "In a game"},
				{ID: 303, RiddleID: 102, Text: "In a puzzle"},
				{ID: 304, RiddleID: 102, Text: "When time resets"},
			},
			Hints: []database.Hint{
				{ID: 93, RiddleID: 102, Text: "It's related to time."},
				{ID: 94, RiddleID: 102, Text: "Think about a circular device."},
			},
		},
		{
			ID:          104,
			Question:    "Say my name and I am no more. What am I?",
			Answer:      "Silence",
			Explanation: "When you speak or break silence, it ceases to exist.",
			Category:    "General",
			Difficulty:  "medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 305, RiddleID: 104, Text: "Silence"},
				{ID: 306, RiddleID: 104, Text: "Echo"},
				{ID: 307, RiddleID: 104, Text: "A shadow"},
				{ID: 308, RiddleID: 104, Text: "A secret"},
			},
			Hints: []database.Hint{
				{ID: 95, RiddleID: 104, Text: "It involves sound or the lack of it."},
				{ID: 96, RiddleID: 104, Text: "Think about the absence of noise."},
			},
		},
		{
			ID:          105,
			Question:    "What can you hold in your right hand but never in your left hand?",
			Answer:      "Your left hand",
			Explanation: "You can't physically hold your own left hand with your left hand.",
			Category:    "Logic",
			Difficulty:  "Easy",
			Points:      5,
			Choices: []database.Choice{
				{ID: 309, RiddleID: 105, Text: "Your left hand"},
				{ID: 310, RiddleID: 105, Text: "Your shadow"},
				{ID: 311, RiddleID: 105, Text: "A mirror"},
				{ID: 312, RiddleID: 105, Text: "Your right hand"},
			},
			Hints: []database.Hint{
				{ID: 97, RiddleID: 105, Text: "It's part of your body."},
				{ID: 98, RiddleID: 105, Text: "Think about opposites."},
			},
		},
		{
			ID:          106,
			Question:    "What can be larger than you without weighing anything?",
			Answer:      "Your shadow",
			Explanation: "A shadow can be larger than you, yet it has no weight.",
			Category:    "Logic",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 313, RiddleID: 106, Text: "Your shadow"},
				{ID: 314, RiddleID: 106, Text: "An idea"},
				{ID: 315, RiddleID: 106, Text: "Air"},
				{ID: 316, RiddleID: 106, Text: "Your reflection"},
			},
			Hints: []database.Hint{
				{ID: 99, RiddleID: 106, Text: "It appears when light shines on you."},
				{ID: 100, RiddleID: 106, Text: "It's intangible but visible."},
			},
		},
		{
			ID:          107,
			Question:    "What do Henry the Eighth and Kermit the Frog have in common?",
			Answer:      "They both have the same middle name: 'The'",
			Explanation: "Both 'Henry the Eighth' and 'Kermit the Frog' have 'The' as their middle name.",
			Category:    "Word",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 317, RiddleID: 107, Text: "The same middle name"},
				{ID: 318, RiddleID: 107, Text: "They are both royalty"},
				{ID: 319, RiddleID: 107, Text: "They both sing"},
				{ID: 320, RiddleID: 107, Text: "They are both famous"},
			},
			Hints: []database.Hint{
				{ID: 101, RiddleID: 107, Text: "Pay attention to their full names."},
				{ID: 102, RiddleID: 107, Text: "The answer involves a word in their names."},
			},
		},
		{
			ID:          108,
			Question:    "What is the only word that is spelled wrong in the dictionary?",
			Answer:      "Wrong",
			Explanation: "The word 'wrong' is intentionally spelled out as 'wrong' in the dictionary.",
			Category:    "Wordplay",
			Difficulty:  "Easy",
			Points:      5,
			Choices: []database.Choice{
				{ID: 321, RiddleID: 108, Text: "Wrong"},
				{ID: 322, RiddleID: 108, Text: "Misspelled"},
				{ID: 323, RiddleID: 108, Text: "Error"},
				{ID: 324, RiddleID: 108, Text: "Typo"},
			},
			Hints: []database.Hint{
				{ID: 103, RiddleID: 108, Text: "It's not a mistake."},
				{ID: 104, RiddleID: 108, Text: "Think about the word 'wrong' itself."},
			},
		},
		{
			ID:          109,
			Question:    "I am in life but not in death. You can't have fun without me. What am I?",
			Answer:      "The letter F",
			Explanation: "The letter F is present in 'life' and 'fun' but not in 'death.'",
			Category:    "Word",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 325, RiddleID: 109, Text: "The letter F"},
				{ID: 326, RiddleID: 109, Text: "Joy"},
				{ID: 327, RiddleID: 109, Text: "Happiness"},
				{ID: 328, RiddleID: 109, Text: "Light"},
			},
			Hints: []database.Hint{
				{ID: 104, RiddleID: 109, Text: "It's part of the alphabet."},
				{ID: 105, RiddleID: 109, Text: "Think about the word 'fun.'"},
			},
		},
		{
			ID:          110,
			Question:    "What does everyone know how to open but not how to close?",
			Answer:      "An egg",
			Explanation: "Once you break an egg `open egg` you can't close it",
			Category:    "Logic",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 326, RiddleID: 110, Text: "A can of worms"},
				{ID: 327, RiddleID: 110, Text: "An egg"},
				{ID: 328, RiddleID: 110, Text: "A secret"},
				{ID: 329, RiddleID: 110, Text: "A book"},
			},
			Hints: []database.Hint{
				{ID: 106, RiddleID: 110, Text: "Thnk of something once you break it you can not mend it."},
			},
		},
		{
			ID:          111,
			Question:    "I start with E and end with E. I have whole countries inside me. What am I?",
			Answer:      "An envelope",
			Explanation: "An envelope starts and ends with 'E' and can contain letters with information about countries.",
			Category:    "Wordplay",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 330, RiddleID: 111, Text: "An envelope"},
				{ID: 331, RiddleID: 111, Text: "An egg"},
				{ID: 332, RiddleID: 111, Text: "Europe"},
				{ID: 333, RiddleID: 111, Text: "A map"},
			},
			Hints: []database.Hint{
				{ID: 107, RiddleID: 111, Text: "It's something you can mail."},
				{ID: 108, RiddleID: 111, Text: "It holds contents inside."},
			},
		},
		{
			ID:          112,
			Question:    "I never speak unless spoken to. Many have heard me but none have seen me. What am I?",
			Answer:      "An echo",
			Explanation: "An echo only responds when a sound is made, and it is heard but not seen.",
			Category:    "Abstract",
			Difficulty:  "Easy",
			Points:      5,
			Choices: []database.Choice{
				{ID: 334, RiddleID: 112, Text: "An echo"},
				{ID: 335, RiddleID: 112, Text: "A shadow"},
				{ID: 336, RiddleID: 112, Text: "A ghost"},
				{ID: 337, RiddleID: 112, Text: "A secret"},
			},
			Hints: []database.Hint{
				{ID: 109, RiddleID: 112, Text: "It involves sound."},
				{ID: 109, RiddleID: 112, Text: "It bounces back at you."},
			},
		},
		{
			ID:          113,
			Question:    "What can fill an entire room without taking up any space?",
			Answer:      "Light",
			Explanation: "Light can fill a room completely without occupying physical space.",
			Category:    "Abstract",
			Difficulty:  "Easy",
			Points:      5,
			Choices: []database.Choice{
				{ID: 100000, RiddleID: 113, Text: "Light"},
				{ID: 200000, RiddleID: 113, Text: "Air"},
				{ID: 300000, RiddleID: 113, Text: "Sound"},
				{ID: 400000, RiddleID: 113, Text: "A shadow"},
			},
			Hints: []database.Hint{
				{ID: 1000000, RiddleID: 113, Text: "It is something you can see."},
				{ID: 2000000, RiddleID: 113, Text: "It can be turned on or off."},
			},
		},
		{
			ID:          114,
			Question:    "I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. What am I?",
			Answer:      "An echo",
			Explanation: "An echo exists as a sound without physical form, carried by the wind.",
			Category:    "General",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 338, RiddleID: 114, Text: "An echo"},
				{ID: 339, RiddleID: 114, Text: "A shadow"},
				{ID: 340, RiddleID: 114, Text: "A whistle"},
				{ID: 341, RiddleID: 114, Text: "A ghost"},
			},
			Hints: []database.Hint{
				{ID: 110, RiddleID: 114, Text: "It's intangible but audible."},
				{ID: 111, RiddleID: 114, Text: "It reflects sound waves."},
			},
		},
		{
			ID:          115,
			Question:    "You measure my life in hours, and I serve you by expiring. I am quick when I am thin and slow when I am fat. The wind is my enemy. What am I?",
			Answer:      "A candle",
			Explanation: "A candle burns and melts as it serves its purpose, and wind can extinguish it.",
			Category:    "Logic",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 342, RiddleID: 115, Text: "A candle"},
				{ID: 343, RiddleID: 115, Text: "A clock"},
				{ID: 344, RiddleID: 115, Text: "A battery"},
				{ID: 345, RiddleID: 115, Text: "A shadow"},
			},
			Hints: []database.Hint{
				{ID: 112, RiddleID: 115, Text: "It gives light."},
				{ID: 113, RiddleID: 115, Text: "It melts as time passes."},
			},
		},
		{
			ID:          116,
			Question:    "Three different doctors said that Paul is their brother, yet Paul claims he has no brothers. Who is lying?",
			Answer:      "No one, the doctors are Paul's sisters",
			Explanation: "The doctors are Paul's sisters, so no one is lying.",
			Category:    "Logic",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 346, RiddleID: 116, Text: "No one, the doctors are Paul's sisters"},
				{ID: 347, RiddleID: 116, Text: "Paul is lying"},
				{ID: 348, RiddleID: 116, Text: "The doctors are lying"},
				{ID: 349, RiddleID: 116, Text: "Paul has amnesia"},
			},
			Hints: []database.Hint{
				{ID: 114, RiddleID: 116, Text: "Think about female doctors."},
				{ID: 115, RiddleID: 116, Text: "Paul's siblings don't have to be brothers."},
			},
		},
		{
			ID:          117,
			Question:    "How many letters are in the alphabet?",
			Answer:      "11 letters",
			Explanation: "The phrase 'the alphabet' has 11 letters in total.",
			Category:    "Word",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 350, RiddleID: 117, Text: "11 letters"},
				{ID: 351, RiddleID: 117, Text: "26 letters"},
				{ID: 352, RiddleID: 117, Text: "13 letters"},
				{ID: 353, RiddleID: 117, Text: "8 letters"},
			},
			Hints: []database.Hint{
				{ID: 116, RiddleID: 117, Text: "Don't think about the actual alphabet."},
				{ID: 117, RiddleID: 117, Text: "Count the letters in the phrase itself."},
			},
		},
		{
			ID:          119,
			Question:    "I have cities, but no houses. I have mountains, but no trees. I have water, but no fish. What am I?",
			Answer:      "A map",
			Explanation: "A map represents cities, mountains, and water but doesn't contain any physical elements.",
			Category:    "Logic",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 358, RiddleID: 119, Text: "A map"},
				{ID: 359, RiddleID: 119, Text: "A globe"},
				{ID: 360, RiddleID: 119, Text: "A book"},
				{ID: 361, RiddleID: 119, Text: "An atlas"},
			},
			Hints: []database.Hint{
				{ID: 120, RiddleID: 119, Text: "It's used for navigation."},
				{ID: 121, RiddleID: 119, Text: "It shows the layout of places."},
			},
		},
		{
			ID:          120,
			Question:    "You see a boat filled with people. It has not sunk, but when you look again, you don't see a single person on the boat. Why?",
			Answer:      "All the people were married",
			Explanation: "The riddle plays on the word 'single,' meaning unmarried. Everyone on the boat is married.",
			Category:    "Logic",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 362, RiddleID: 120, Text: "All the people were married"},
				{ID: 363, RiddleID: 120, Text: "The people hid below deck"},
				{ID: 364, RiddleID: 120, Text: "The boat was empty"},
				{ID: 365, RiddleID: 120, Text: "The boat disappeared"},
			},
			Hints: []database.Hint{
				{ID: 122, RiddleID: 120, Text: "It's a play on the word 'single.'"},
				{ID: 123, RiddleID: 120, Text: "Consider marital status."},
			},
		},
		{
			ID:          121,
			Question:    "Mr. Taylor has four daughters, and each has a brother. In total, how many children does Mr. Taylor have?",
			Answer:      "Five children",
			Explanation: "Each daughter shares the same brother, so there are four daughters and one son, totaling five children.",
			Category:    "Logic",
			Difficulty:  "Hard",
			Points:      15,
			Choices: []database.Choice{
				{ID: 366, RiddleID: 121, Text: "Five children"},
				{ID: 367, RiddleID: 121, Text: "Eight children"},
				{ID: 368, RiddleID: 121, Text: "Four children"},
				{ID: 369, RiddleID: 121, Text: "Six children"},
			},
			Hints: []database.Hint{
				{ID: 124, RiddleID: 121, Text: "Each daughter shares the same brother."},
				{ID: 125, RiddleID: 121, Text: "Count carefully; there is only one brother."},
			},
		},
		{
			ID:          122,
			Question:    "What can run but never walk, have a mouth but never talk, have a head that never weeps, and a bed that never sleeps?",
			Answer:      "A river",
			Explanation: "A river flows (runs) without walking, has a mouth and head as features, and a bed where it flows.",
			Category:    "Logic",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 370, RiddleID: 122, Text: "A clock"},
				{ID: 371, RiddleID: 122, Text: "A river"},
				{ID: 372, RiddleID: 122, Text: "A shadow"},
				{ID: 373, RiddleID: 122, Text: "A mountain"},
			},
			Hints: []database.Hint{
				{ID: 126, RiddleID: 122, Text: "It has a mouth and flows."},
				{ID: 127, RiddleID: 122, Text: "It’s a natural water body."},
			},
		},
		{
			ID:          123,
			Question:    "If an electric train is moving north at 55 mph and the wind is blowing east at 70 mph, which way does the smoke blow?",
			Answer:      "Electric trains don't produce smoke",
			Explanation: "Electric trains run on electricity and do not emit smoke.",
			Category:    "Logic",
			Difficulty:  "Easy",
			Points:      5,
			Choices: []database.Choice{
				{ID: 374, RiddleID: 123, Text: "In all directions from the smokestack"},
				{ID: 375, RiddleID: 123, Text: "Depends on the wind direction"},
				{ID: 376, RiddleID: 123, Text: "Southwest"},
				{ID: 377, RiddleID: 123, Text: "Electric trains don't produce smoke"},
			},
			Hints: []database.Hint{
				{ID: 128, RiddleID: 123, Text: "Think about the type of train."},
				{ID: 129, RiddleID: 123, Text: "Does an electric train emit smoke?"},
			},
		},
		{
			ID:          124,
			Question:    "There are 6 sisters. Each sister has 1 brother. How many brothers are in the sister's family?",
			Answer:      "1 brother",
			Explanation: "All the sisters share the same one brother.",
			Category:    "Logic",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 378, RiddleID: 124, Text: "1 brother"},
				{ID: 379, RiddleID: 124, Text: "6 brothers"},
				{ID: 380, RiddleID: 124, Text: "7 brothers"},
				{ID: 381, RiddleID: 124, Text: "None"},
			},
			Hints: []database.Hint{
				{ID: 130, RiddleID: 124, Text: "The same brother is shared by all the sisters."},
				{ID: 131, RiddleID: 124, Text: "Count carefully; it's not 6."},
			},
		},
		{
			ID:          125,
			Question:    "Two fathers and two sons come home from the mall. Yet when they arrive home, only three people get out of the car. How is this possible?",
			Answer:      "They are a grandfather, father, and son",
			Explanation: "The group consists of a grandfather, his son (the father), and his grandson. This makes three people but includes two fathers and two sons.",
			Category:    "Logic",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 382, RiddleID: 125, Text: "They are a grandfather, father, and son"},
				{ID: 383, RiddleID: 125, Text: "One person stayed in the car"},
				{ID: 384, RiddleID: 125, Text: "They were triplets"},
				{ID: 385, RiddleID: 125, Text: "It’s a trick question"},
			},
			Hints: []database.Hint{
				{ID: 132, RiddleID: 125, Text: "One person is both a father and a son."},
				{ID: 133, RiddleID: 125, Text: "Think about generations."},
			},
		},
		{
			ID:          126,
			Question:    "A murderer is condemned to death and has the option to die in one of the following three rooms: a room full of raging fire, a room full of assassins with loaded guns, and a room full of lions who haven't eaten in years. Which room should he choose?",
			Answer:      "The room full of lions who haven't eaten in years",
			Explanation: "Lions that haven't eaten in years would be dead, making the room safe.",
			Category:    "Logic",
			Difficulty:  "Hard",
			Points:      15,
			Choices: []database.Choice{
				{ID: 386, RiddleID: 126, Text: "The room full of lions who haven't eaten in years"},
				{ID: 387, RiddleID: 126, Text: "The room full of assassins"},
				{ID: 388, RiddleID: 126, Text: "The room full of raging fire"},
				{ID: 389, RiddleID: 126, Text: "None of the rooms"},
			},
			Hints: []database.Hint{
				{ID: 134, RiddleID: 126, Text: "Lions can't survive for years without food."},
				{ID: 135, RiddleID: 126, Text: "One of the rooms is safer than it seems."},
			},
		},
		{
			ID:          127,
			Question:    "If you eat me, my sender will eat you. What am I?",
			Answer:      "Fishhook",
			Explanation: "If you eat the bait on the fishhook, the fisherman (the sender) will eat you, the fish.",
			Category:    "General",
			Difficulty:  "Hard",
			Points:      15,
			Choices: []database.Choice{
				{ID: 390, RiddleID: 127, Text: "Apple"},
				{ID: 391, RiddleID: 127, Text: "Fishhook"},
				{ID: 392, RiddleID: 127, Text: "Worm"},
				{ID: 393, RiddleID: 127, Text: "Trap"},
			},
			Hints: []database.Hint{
				{ID: 136, RiddleID: 127, Text: "It’s used by fishermen."},
				{ID: 137, RiddleID: 127, Text: "It’s designed to catch fish."},
			},
		},
		{
			ID:          128,
			Question:    "Steve was murdered on Saturday afternoon. His wife said she was reading. The doorman said he was in the shower. The chef said he was making breakfast. The gardener was pruning hedges. From the information given, who committed the murder?",
			Answer:      "The chef",
			Explanation: "The chef claimed to be making breakfast in the afternoon, which doesn’t add up.",
			Category:    "Logic",
			Difficulty:  "Hard",
			Points:      10,
			Choices: []database.Choice{
				{ID: 394, RiddleID: 128, Text: "The wife"},
				{ID: 395, RiddleID: 128, Text: "The chef"},
				{ID: 396, RiddleID: 128, Text: "The gardener"},
				{ID: 397, RiddleID: 128, Text: "The doorman"},
			},
			Hints: []database.Hint{
				{ID: 138, RiddleID: 128, Text: "Focus on the timeline of events."},
				{ID: 139, RiddleID: 128, Text: "Breakfast doesn’t happen in the afternoon."},
			},
		},
		{
			ID:          129,
			Question:    "If a plane came crashing down on the border between Canada and America, where are the survivors buried?",
			Answer:      "Survivors aren’t buried",
			Explanation: "Survivors are alive and are not buried.",
			Category:    "General",
			Difficulty:  "Easy",
			Points:      5,
			Choices: []database.Choice{
				{ID: 398, RiddleID: 129, Text: "In Canada"},
				{ID: 399, RiddleID: 129, Text: "In America"},
				{ID: 400, RiddleID: 129, Text: "Survivors aren’t buried"},
				{ID: 401, RiddleID: 129, Text: "At the border"},
			},
			Hints: []database.Hint{
				{ID: 140, RiddleID: 129, Text: "Think about the meaning of survivors."},
				{ID: 141, RiddleID: 129, Text: "Survivors are alive."},
			},
		},
		{
			ID:          130,
			Question:    "The more these are taken, the more they are left behind. What are they?",
			Answer:      "Footsteps",
			Explanation: "When you take steps (footsteps), they leave a trail behind you.",
			Category:    "General",
			Difficulty:  "Hard",
			Points:      15,
			Choices: []database.Choice{
				{ID: 402, RiddleID: 130, Text: "Footsteps"},
				{ID: 403, RiddleID: 130, Text: "Memories"},
				{ID: 404, RiddleID: 130, Text: "Time"},
				{ID: 405, RiddleID: 130, Text: "Shadow"},
			},
			Hints: []database.Hint{
				{ID: 142, RiddleID: 130, Text: "Think about something you leave behind when walking."},
				{ID: 143, RiddleID: 130, Text: "They form a trail."},
			},
		},
		{
			ID:          132,
			Question:    "What is caught but never thrown?",
			Answer:      "A cold",
			Explanation: "You catch a cold, but you don’t throw it.",
			Category:    "General",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 410, RiddleID: 132, Text: "A ball"},
				{ID: 411, RiddleID: 132, Text: "A cold"},
				{ID: 412, RiddleID: 132, Text: "A fish"},
				{ID: 413, RiddleID: 132, Text: "An idea"},
			},
			Hints: []database.Hint{
				{ID: 146, RiddleID: 132, Text: "Think about illnesses."},
				{ID: 147, RiddleID: 132, Text: "You don’t throw this."},
			},
		},
		{
			ID:          133,
			Question:    "Humans purchase me to eat but then never eat me. What am I?",
			Answer:      "Plate",
			Explanation: "Plates are purchased to hold food for eating, but people don’t eat the plates themselves.",
			Category:    "General",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 414, RiddleID: 133, Text: "Plate"},
				{ID: 415, RiddleID: 133, Text: "Napkin"},
				{ID: 416, RiddleID: 133, Text: "Spoon"},
				{ID: 417, RiddleID: 133, Text: "Fork"},
			},
			Hints: []database.Hint{
				{ID: 148, RiddleID: 133, Text: "It holds the food but isn’t edible."},
				{ID: 149, RiddleID: 133, Text: "It’s part of tableware."},
			},
		},
		{
			ID:          134,
			Question:    "What is more useful when it is broken?",
			Answer:      "Egg",
			Explanation: "An egg becomes useful when it is broken for cooking or eating.",
			Category:    "Logic",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 418, RiddleID: 134, Text: "Egg"},
				{ID: 419, RiddleID: 134, Text: "Glass"},
				{ID: 420, RiddleID: 134, Text: "Code"},
				{ID: 421, RiddleID: 134, Text: "Chain"},
			},
			Hints: []database.Hint{
				{ID: 150, RiddleID: 134, Text: "It’s often used in breakfast meals."},
				{ID: 151, RiddleID: 134, Text: "It has a shell."},
			},
		},
		{
			ID:          135,
			Question:    "I am easy to lift, but hard to throw. What am I?",
			Answer:      "Feather",
			Explanation: "A feather is light and easy to lift, but because it’s so light, it’s hard to throw.",
			Category:    "General",
			Difficulty:  "Easy",
			Points:      5,
			Choices: []database.Choice{
				{ID: 422, RiddleID: 135, Text: "Feather"},
				{ID: 423, RiddleID: 135, Text: "Balloon"},
				{ID: 424, RiddleID: 135, Text: "Paper"},
				{ID: 425, RiddleID: 135, Text: "Cotton"},
			},
			Hints: []database.Hint{
				{ID: 152, RiddleID: 135, Text: "It’s very light."},
				{ID: 153, RiddleID: 135, Text: "It’s from a bird."},
			},
		},
		{
			ID:          136,
			Question:    "What goes up, but never comes down?",
			Answer:      "Age",
			Explanation: "As time passes, age increases but never decreases.",
			Category:    "Logic",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 426, RiddleID: 136, Text: "Age"},
				{ID: 427, RiddleID: 136, Text: "Smoke"},
				{ID: 428, RiddleID: 136, Text: "Balloon"},
				{ID: 429, RiddleID: 136, Text: "Cloud"},
			},
			Hints: []database.Hint{
				{ID: 154, RiddleID: 136, Text: "It’s measured in years."},
				{ID: 155, RiddleID: 136, Text: "Everyone has one."},
			},
		},
		{
			ID:          137,
			Question:    "A bus driver goes the wrong way down a one-way street. He passes the cops, but they do not stop him. Why?",
			Answer:      "He was walking",
			Explanation: "The bus driver was walking, not driving, so he wasn’t breaking any traffic laws.",
			Category:    "General",
			Difficulty:  "Easy",
			Points:      5,
			Choices: []database.Choice{
				{ID: 430, RiddleID: 137, Text: "He was walking"},
				{ID: 431, RiddleID: 137, Text: "The cops didn’t notice"},
				{ID: 432, RiddleID: 137, Text: "The street was empty"},
				{ID: 433, RiddleID: 137, Text: "He had special permission"},
			},
			Hints: []database.Hint{
				{ID: 156, RiddleID: 137, Text: "He wasn’t driving a vehicle."},
				{ID: 157, RiddleID: 137, Text: "Think of an alternate way of moving."},
			},
		},
		{
			ID:          138,
			Question:    "I am a five-letter word and people eat me. If you remove the first letter I become an energy form. If you remove the first two letters, I am needed to live. Scramble the last three letters and I am a drink. What word am I?",
			Answer:      "Wheat",
			Explanation: "Wheat is eaten. Removing letters forms heat (energy) and eat (needed to live), and scrambling tea gives a drink.",
			Category:    "Word",
			Difficulty:  "Hard",
			Points:      15,
			Choices: []database.Choice{
				{ID: 434, RiddleID: 138, Text: "Wheat"},
				{ID: 435, RiddleID: 138, Text: "Bread"},
				{ID: 436, RiddleID: 138, Text: "Corn"},
				{ID: 437, RiddleID: 138, Text: "Rice"},
			},
			Hints: []database.Hint{
				{ID: 158, RiddleID: 138, Text: "It’s a grain."},
				{ID: 159, RiddleID: 138, Text: "It’s used to make flour."},
			},
		},
		{
			ID:          139,
			Question:    "What do we call a woman who always knows her husband’s whereabouts all the time?",
			Answer:      "Widow",
			Explanation: "A widow knows where her husband is because he has passed away.",
			Category:    "General",
			Difficulty:  "Hard",
			Points:      10,
			Choices: []database.Choice{
				{ID: 438, RiddleID: 139, Text: "Detective"},
				{ID: 439, RiddleID: 139, Text: "Widow"},
				{ID: 440, RiddleID: 139, Text: "Psychic"},
				{ID: 441, RiddleID: 139, Text: "Tracker"},
			},
			Hints: []database.Hint{
				{ID: 160, RiddleID: 139, Text: "Think about a permanent state of knowledge."},
				{ID: 161, RiddleID: 139, Text: "Her husband is no longer alive."},
			},
		},
		{
			ID:          140,
			Question:    "A Woman is sitting in her hotel room when someone knocks at the door. She opened the door to find a man she's never seen before. He says, 'Oh I am sorry, I made a mistake and thought this was my room.' He then ran away and got into an elevator so the woman shut her door and phoned security. What made the woman so suspicious?",
			Answer:      "He knocked on the door instead of trying to open it with a key.",
			Explanation: "A guest in a hotel would usually have a key to their own room and would not knock on their own door.",
			Category:    "Logic",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 442, RiddleID: 140, Text: "He didn't introduce himself."},
				{ID: 443, RiddleID: 140, Text: "He knocked instead of using a key."},
				{ID: 444, RiddleID: 140, Text: "He looked nervous."},
				{ID: 445, RiddleID: 140, Text: "He was not dressed like a guest."},
			},
			Hints: []database.Hint{
				{ID: 162, RiddleID: 140, Text: "Consider typical hotel behavior."},
				{ID: 163, RiddleID: 140, Text: "Guests usually have room keys."},
			},
		},
		{
			ID:          141,
			Question:    "Rachel goes to the supermarket and buys 10 tomatoes. Unfortunately, on the way back home, all but 9 get ruined. How many tomatoes are left in a good condition?",
			Answer:      "9",
			Explanation: "The phrase 'all but 9' means that 9 tomatoes are still in good condition.",
			Category:    "Trick Question",
			Difficulty:  "Easy",
			Points:      5,
			Choices: []database.Choice{
				{ID: 446, RiddleID: 141, Text: "1"},
				{ID: 447, RiddleID: 141, Text: "9"},
				{ID: 448, RiddleID: 141, Text: "10"},
				{ID: 449, RiddleID: 141, Text: "0"},
			},
			Hints: []database.Hint{
				{ID: 164, RiddleID: 141, Text: "Focus on the meaning of 'all but'."},
				{ID: 165, RiddleID: 141, Text: "It's not a math problem, it's about the wording."},
			},
		},
		{
			ID:          142,
			Question:    "If you multiply this number by any other number, the answer will always be the same. What number is this?",
			Answer:      "0",
			Explanation: "Multiplying any number by 0 results in 0.",
			Category:    "Mathematics",
			Difficulty:  "Easy",
			Points:      5,
			Choices: []database.Choice{
				{ID: 450, RiddleID: 142, Text: "1"},
				{ID: 451, RiddleID: 142, Text: "0"},
				{ID: 452, RiddleID: 142, Text: "Infinity"},
				{ID: 453, RiddleID: 142, Text: "None of the above"},
			},
			Hints: []database.Hint{
				{ID: 166, RiddleID: 142, Text: "What happens when multiplying by 0?"},
			},
		},
		{
			ID:          143,
			Question:    "Two girls were born to the same mother, on the same day, at the same time, in the same month and year, and yet they're not twins. How can this be?",
			Answer:      "They are triplets.",
			Explanation: "If two girls are born as part of a set of triplets, they are not considered twins.",
			Category:    "Logic",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 454, RiddleID: 143, Text: "They are twins."},
				{ID: 455, RiddleID: 143, Text: "They are triplets."},
				{ID: 456, RiddleID: 143, Text: "They were adopted."},
				{ID: 457, RiddleID: 143, Text: "It was a coincidence."},
			},
			Hints: []database.Hint{
				{ID: 167, RiddleID: 143, Text: "Consider other possible sibling configurations."},
				{ID: 168, RiddleID: 143, Text: "Twins aren't the only possibility for simultaneous births."},
			},
		},
		{
			ID:          144,
			Question:    "I move very slowly at an imperceptible rate, although I take my time, I am never late. I accompany life and survive past demise; I am viewed with esteem in many women's eyes. What am I?",
			Answer:      "A age.",
			Explanation: "A diamond forms slowly, lasts forever, and is highly valued by many.",
			Category:    "Riddle",
			Difficulty:  "Hard",
			Points:      15,
			Choices: []database.Choice{
				{ID: 458, RiddleID: 144, Text: "A diamond"},
				{ID: 459, RiddleID: 144, Text: "Time"},
				{ID: 460, RiddleID: 144, Text: "A snail"},
				{ID: 461, RiddleID: 144, Text: "A age"},
			},
			Hints: []database.Hint{
				{ID: 170, RiddleID: 144, Text: "Think of what most women lie about."},
			},
		},
		{
			ID:          145,
			Question:    "Who has married many women but was never married?",
			Answer:      "A priest",
			Explanation: "A priest officiates weddings and marries people, but he himself is not married.",
			Category:    "Logic",
			Difficulty:  "Hard",
			Points:      15,
			Choices: []database.Choice{
				{ID: 462, RiddleID: 145, Text: "A lawyer"},
				{ID: 463, RiddleID: 145, Text: "A priest"},
				{ID: 464, RiddleID: 145, Text: "A matchmaker"},
				{ID: 465, RiddleID: 145, Text: "A magician"},
			},
			Hints: []database.Hint{
				{ID: 171, RiddleID: 145, Text: "This person is often seen at weddings."},
				{ID: 172, RiddleID: 145, Text: "He marries others but remains unmarried himself."},
			},
		},
		{
			ID:          146,
			Question:    "What does a man do only once in his lifetime, but women do once a year after they are 29?",
			Answer:      "Turn 30",
			Explanation: "A man turns 30 only once in his life, but women, jokingly, claim to turn 30 every year after reaching that age.",
			Category:    "Word",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 466, RiddleID: 146, Text: "Celebrate a milestone"},
				{ID: 467, RiddleID: 146, Text: "Turn 30"},
				{ID: 468, RiddleID: 146, Text: "Retire"},
				{ID: 469, RiddleID: 146, Text: "Nothing"},
			},
			Hints: []database.Hint{
				{ID: 173, RiddleID: 146, Text: "Think about an age milestone."},
				{ID: 174, RiddleID: 146, Text: "It’s a humorous take on turning 30."},
			},
		},
		{
			ID:          147,
			Question:    "Poor people have it. Rich people do not need it. If you eat it, you die. What is it?",
			Answer:      "Nothing",
			Explanation: "Poor people have nothing. Rich people don't need nothing, and eating nothing leads to starvation.",
			Category:    "General",
			Difficulty:  "Hard",
			Points:      5,
			Choices: []database.Choice{
				{ID: 470, RiddleID: 147, Text: "Hunger"},
				{ID: 471, RiddleID: 147, Text: "Nothing"},
				{ID: 472, RiddleID: 147, Text: "Love"},
				{ID: 473, RiddleID: 147, Text: "Silence"},
			},
			Hints: []database.Hint{
				{ID: 175, RiddleID: 147, Text: "Focus on the concept of 'nothing.'"},
				{ID: 176, RiddleID: 147, Text: "Eating nothing means starvation."},
			},
		},
		{
			ID:          148,
			Question:    "They come out at night without being called, and are lost in the day without being stolen. What are they?",
			Answer:      "Stars",
			Explanation: "Stars are visible at night and disappear during the day due to sunlight.",
			Category:    "General",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 474, RiddleID: 148, Text: "Dreams"},
				{ID: 475, RiddleID: 148, Text: "Stars"},
				{ID: 476, RiddleID: 148, Text: "Fireflies"},
				{ID: 477, RiddleID: 148, Text: "Owls"},
			},
			Hints: []database.Hint{
				{ID: 177, RiddleID: 148, Text: "Think about the night sky."},
				{ID: 178, RiddleID: 148, Text: "They disappear during the day."},
			},
		},
		{
			ID:          149,
			Question:    "What is always in front of you, but cannot be seen?",
			Answer:      "The future",
			Explanation: "The future lies ahead but is always unseen.",
			Category:    "General",
			Difficulty:  "Medium",
			Points:      5,
			Choices: []database.Choice{
				{ID: 478, RiddleID: 149, Text: "Air"},
				{ID: 479, RiddleID: 149, Text: "The future"},
				{ID: 480, RiddleID: 149, Text: "Time"},
				{ID: 481, RiddleID: 149, Text: "A shadow"},
			},
			Hints: []database.Hint{
				{ID: 179, RiddleID: 149, Text: "It’s about time."},
				{ID: 180, RiddleID: 149, Text: "It’s always ahead of you."},
			},
		},
		{
			ID:          150,
			Question:    "What goes through cities and fields, but never moves?",
			Answer:      "A road",
			Explanation: "Roads stretch through cities and fields but remain stationary.",
			Category:    "Logic",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 482, RiddleID: 150, Text: "A river"},
				{ID: 483, RiddleID: 150, Text: "A road"},
				{ID: 484, RiddleID: 150, Text: "Wind"},
				{ID: 485, RiddleID: 150, Text: "A bridge"},
			},
			Hints: []database.Hint{
				{ID: 181, RiddleID: 150, Text: "Think about infrastructure."},
				{ID: 182, RiddleID: 150, Text: "It connects places."},
			},
		},
		{
			ID:          151,
			Question:    "What 2 things can you never eat for breakfast?",
			Answer:      "Lunch and dinner",
			Explanation: "Lunch and dinner are meals that are not eaten at breakfast time.",
			Category:    "Word",
			Difficulty:  "Easy",
			Points:      5,
			Choices: []database.Choice{
				{ID: 486, RiddleID: 151, Text: "Lunch and dinner"},
				{ID: 487, RiddleID: 151, Text: "Dessert and snacks"},
				{ID: 488, RiddleID: 151, Text: "Meat and bread"},
				{ID: 489, RiddleID: 151, Text: "Water and coffee"},
			},
			Hints: []database.Hint{
				{ID: 183, RiddleID: 151, Text: "It’s about meals."},
			},
		},
		{
			ID:          152,
			Question:    "What is always on its way but never arrives?",
			Answer:      "Tomorrow",
			Explanation: "Tomorrow is always ahead and never actually arrives.",
			Category:    "General",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 490, RiddleID: 152, Text: "A letter"},
				{ID: 491, RiddleID: 152, Text: "Tomorrow"},
				{ID: 492, RiddleID: 152, Text: "The future"},
				{ID: 493, RiddleID: 152, Text: "A train"},
			},
			Hints: []database.Hint{
				{ID: 184, RiddleID: 152, Text: "Think about time."},
			},
		},
		{
			ID:          153,
			Question:    "What word in the English language fulfills all the following criteria: The first two letters signify a male, the first three letters signify a female, the first four letters signify a great person, while the entire word signifies a great woman?",
			Answer:      "Heroine",
			Explanation: "The word 'heroine' meets all the described conditions.",
			Category:    "Word",
			Difficulty:  "Hard",
			Points:      15,
			Choices: []database.Choice{
				{ID: 494, RiddleID: 153, Text: "Heroine"},
				{ID: 495, RiddleID: 153, Text: "Queen"},
				{ID: 496, RiddleID: 153, Text: "Princess"},
				{ID: 497, RiddleID: 153, Text: "Duchess"},
			},
			Hints: []database.Hint{
				{ID: 185, RiddleID: 153, Text: "Think about the structure of the word."},
				{ID: 186, RiddleID: 153, Text: "The word describes a great woman."},
			},
		},
		{
			ID:          154,
			Question:    "What English word retains the same pronunciation, even after you take away four of its five letters?",
			Answer:      "Queue",
			Explanation: "The word 'queue' is pronounced the same way even if you remove the last four letters, leaving only 'q.'",
			Category:    "Word",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 498, RiddleID: 154, Text: "Queue"},
				{ID: 499, RiddleID: 154, Text: "Quiet"},
				{ID: 500, RiddleID: 154, Text: "Quest"},
				{ID: 501, RiddleID: 154, Text: "Quaint"},
			},
			Hints: []database.Hint{
				{ID: 187, RiddleID: 154, Text: "It’s a short word with repeated letters."},
				{ID: 188, RiddleID: 154, Text: "Think of something related to a line."},
			},
		},
		{
			ID:          155,
			Question:    "When John was six years old, he hammered a nail into his favorite tree to mark his height. Ten years later at age sixteen, John returned to see how much higher the nail was. If the tree grew by five centimeters each year, how much higher would the nail be?",
			Answer:      "The nail would remain at the same height.",
			Explanation: "Trees grow from their tops, not from the base, so the nail stays at the same height.",
			Category:    "Logic",
			Difficulty:  "Medium",
			Points:      5,
			Choices: []database.Choice{
				{ID: 502, RiddleID: 155, Text: "50 centimeters higher"},
				{ID: 503, RiddleID: 155, Text: "10 centimeters higher"},
				{ID: 504, RiddleID: 155, Text: "The same height"},
				{ID: 505, RiddleID: 155, Text: "5 centimeters higher"},
			},
			Hints: []database.Hint{
				{ID: 189, RiddleID: 155, Text: "Trees grow from their tops, not the base."},
			},
		},
		{
			ID:          156,
			Question:    "I am four times as old as my daughter. In 20 years time, I shall be twice as old as her. How old are we now?",
			Answer:      "I am 40, and my daughter is 10.",
			Explanation: "If I am 40 and my daughter is 10, in 20 years, I will be 60, and she will be 30, making me twice her age.",
			Category:    "Mathematics",
			Difficulty:  "Hard",
			Points:      15,
			Choices: []database.Choice{
				{ID: 506, RiddleID: 156, Text: "I am 40, and my daughter is 10."},
				{ID: 507, RiddleID: 156, Text: "I am 36, and my daughter is 9."},
				{ID: 508, RiddleID: 156, Text: "I am 50, and my daughter is 12."},
				{ID: 509, RiddleID: 156, Text: "I am 30, and my daughter is 8."},
			},
			Hints: []database.Hint{
				{ID: 190, RiddleID: 156, Text: "Set up a proportion between the ages."},
			},
		},
		{
			ID:          157,
			Question:    "Lily is a lilypad in a small pond. Lily doubles her size each day. On the 20th day, she covers the whole pond. On what day was Lily half the size of the pond?",
			Answer:      "On the 19th day.",
			Explanation: "If Lily doubles in size each day, she would have been half the size of the pond the day before it was fully covered.",
			Category:    "Logic",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 510, RiddleID: 157, Text: "The 18th day"},
				{ID: 511, RiddleID: 157, Text: "The 19th day"},
				{ID: 512, RiddleID: 157, Text: "The 10th day"},
				{ID: 513, RiddleID: 157, Text: "The 20th day"},
			},
			Hints: []database.Hint{
				{ID: 191, RiddleID: 157, Text: "Think of how doubling works."},
				{ID: 192, RiddleID: 157, Text: "It would have been half the size the day before full coverage."},
			},
		},
		{
			ID:          158,
			Question:    "I am something people love or hate. I change people's appearances and thoughts. If a person takes care of themselves, I will go up even higher. To some people, I will fool them. To others, I am a mystery. Some people might want to try and hide me, but I will show. No matter how hard people try, I will never go down. What am I?",
			Answer:      "Age",
			Explanation: "Age is something people have mixed feelings about. It changes appearances and cannot be reduced.",
			Category:    "General",
			Difficulty:  "Hard",
			Points:      15,
			Choices: []database.Choice{
				{ID: 514, RiddleID: 158, Text: "Beauty"},
				{ID: 515, RiddleID: 158, Text: "Age"},
				{ID: 516, RiddleID: 158, Text: "Wisdom"},
				{ID: 517, RiddleID: 158, Text: "Time"},
			},
			Hints: []database.Hint{
				{ID: 193, RiddleID: 158, Text: "It increases over time."},
				{ID: 194, RiddleID: 158, Text: "People often try to hide it."},
			},
		},
		{
			ID:          159,
			Question:    "If you have me, you want to share me. If you share me, you don't have me.",
			Answer:      "A secret",
			Explanation: "A secret is something you lose once it's shared.",
			Category:    "Logic",
			Difficulty:  "Hard",
			Points:      15,
			Choices: []database.Choice{
				{ID: 518, RiddleID: 159, Text: "A secret"},
				{ID: 519, RiddleID: 159, Text: "A gift"},
				{ID: 520, RiddleID: 159, Text: "A joke"},
				{ID: 521, RiddleID: 159, Text: "Happiness"},
			},
			Hints: []database.Hint{
				{ID: 195, RiddleID: 159, Text: "It's something private."},
			},
		},
		{
			ID:          160,
			Question:    "How can you drop a raw egg from a height onto a concrete floor without cracking it?",
			Answer:      "The egg won't crack the concrete floor.",
			Explanation: "Concrete floors are hard and won't crack from the impact of a raw egg.",
			Category:    "Logic",
			Difficulty:  "Easy",
			Points:      5,
			Choices: []database.Choice{
				{ID: 522, RiddleID: 160, Text: "The egg won't crack the concrete floor."},
				{ID: 523, RiddleID: 160, Text: "Use a cushion under the egg."},
				{ID: 524, RiddleID: 160, Text: "Drop it gently."},
				{ID: 525, RiddleID: 160, Text: "Boil the egg first."},
			},
			Hints: []database.Hint{
				{ID: 196, RiddleID: 160, Text: "Think about the floor, not the egg."},
			},
		},
		{
			ID:          161,
			Question:    "What tastes better than it smells?",
			Answer:      "A tongue.",
			Explanation: "A tongue can taste flavors but has no sense of smell.",
			Category:    "Word",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 526, RiddleID: 161, Text: "A tongue"},
				{ID: 527, RiddleID: 161, Text: "Candy"},
				{ID: 528, RiddleID: 161, Text: "Soup"},
				{ID: 529, RiddleID: 161, Text: "Honey"},
			},
			Hints: []database.Hint{
				{ID: 197, RiddleID: 161, Text: "It's part of the body."},
				{ID: 198, RiddleID: 161, Text: "It’s involved in tasting."},
			},
		},
		{
			ID:          162,
			Question:    "What building has the most stories?",
			Answer:      "A library.",
			Explanation: "Libraries are filled with stories in the form of books.",
			Category:    "Word",
			Difficulty:  "Easy",
			Points:      5,
			Choices: []database.Choice{
				{ID: 530, RiddleID: 162, Text: "A library"},
				{ID: 531, RiddleID: 162, Text: "A skyscraper"},
				{ID: 532, RiddleID: 162, Text: "A museum"},
				{ID: 533, RiddleID: 162, Text: "A theater"},
			},
			Hints: []database.Hint{
				{ID: 199, RiddleID: 162, Text: "Think about books."},
			},
		},
		{
			ID:          163,
			Question:    "What kind of tree can you carry in your hand?",
			Answer:      "A palm tree.",
			Explanation: "A palm tree shares its name with the palm of your hand.",
			Category:    "Word",
			Difficulty:  "Medium",
			Points:      5,
			Choices: []database.Choice{
				{ID: 534, RiddleID: 163, Text: "A palm tree"},
				{ID: 535, RiddleID: 163, Text: "A bonsai tree"},
				{ID: 536, RiddleID: 163, Text: "A fig tree"},
				{ID: 537, RiddleID: 163, Text: "A tiny tree"},
			},
			Hints: []database.Hint{
				{ID: 200, RiddleID: 163, Text: "It’s part of your hand."},
			},
		},
		{
			ID:          164,
			Question:    "What starts with T, ends with T, and has T in it?",
			Answer:      "A teapot.",
			Explanation: "The word 'teapot' starts and ends with 'T' and contains tea.",
			Category:    "Word",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 538, RiddleID: 164, Text: "A teapot"},
				{ID: 539, RiddleID: 164, Text: "A tent"},
				{ID: 540, RiddleID: 164, Text: "A tablet"},
				{ID: 541, RiddleID: 164, Text: "A t-shirt"},
			},
			Hints: []database.Hint{
				{ID: 201, RiddleID: 164, Text: "It’s related to tea."},
			},
		},
		{
			ID:          165,
			Question:    "Where is the only place where today comes before yesterday?",
			Answer:      "The dictionary.",
			Explanation: "In the dictionary, words are arranged alphabetically, so 'today' comes before 'yesterday.'",
			Category:    "Logic",
			Difficulty:  "Hard",
			Points:      15,
			Choices: []database.Choice{
				{ID: 542, RiddleID: 165, Text: "The dictionary"},
				{ID: 543, RiddleID: 165, Text: "A calendar"},
				{ID: 544, RiddleID: 165, Text: "A clock"},
				{ID: 545, RiddleID: 165, Text: "A timeline"},
			},
			Hints: []database.Hint{
				{ID: 202, RiddleID: 165, Text: "Think about alphabetical order."},
			},
		},
		{
			ID:          166,
			Question:    "What comes at the end of everything?",
			Answer:      "The letter 'g'.",
			Explanation: "The word 'everything' ends with the letter 'g.'",
			Category:    "Word",
			Difficulty:  "Hard",
			Points:      5,
			Choices: []database.Choice{
				{ID: 546, RiddleID: 166, Text: "The letter 'g'"},
				{ID: 547, RiddleID: 166, Text: "A period"},
				{ID: 548, RiddleID: 166, Text: "Silence"},
				{ID: 549, RiddleID: 166, Text: "The end"},
			},
			Hints: []database.Hint{
				{ID: 203, RiddleID: 166, Text: "It’s a single letter."},
			},
		},
		{
			ID:          167,
			Question:    "What do the letter 't' and an island have in common?",
			Answer:      "They are both in the middle of water.",
			Explanation: "The letter 't' is in the word 'water,' just like an island is surrounded by water.",
			Category:    "Word",
			Difficulty:  "Hard",
			Points:      15,
			Choices: []database.Choice{
				{ID: 550, RiddleID: 167, Text: "They are both in the middle of water."},
				{ID: 551, RiddleID: 167, Text: "They are unique."},
				{ID: 552, RiddleID: 167, Text: "They stand alone."},
				{ID: 553, RiddleID: 167, Text: "They are essential."},
			},
			Hints: []database.Hint{
				{ID: 204, RiddleID: 167, Text: "Think about the spelling of 'water.'"},
			},
		},
		{
			ID:          168,
			Question:    "What kind of ship has two mates but no captain?",
			Answer:      "A relationship.",
			Explanation: "A relationship involves two people (mates) and has no captain.",
			Category:    "Word",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 554, RiddleID: 168, Text: "A relationship"},
				{ID: 555, RiddleID: 168, Text: "A friendship"},
				{ID: 556, RiddleID: 168, Text: "A companionship"},
				{ID: 557, RiddleID: 168, Text: "A partnership"},
			},
			Hints: []database.Hint{
				{ID: 205, RiddleID: 168, Text: "It involves two people."},
			},
		},
		{
			ID:          169,
			Question:    "If you throw a blue stone into the Red Sea, what will it become?",
			Answer:      "wet.'",
			Explanation: "it becomes wet.",
			Category:    "Logic",
			Difficulty:  "Hard",
			Points:      15,
			Choices: []database.Choice{
				{ID: 558, RiddleID: 169, Text: "A little green"},
				{ID: 559, RiddleID: 169, Text: "A fish"},
				{ID: 560, RiddleID: 169, Text: "A piece of coral"},
				{ID: 561, RiddleID: 169, Text: "Wet"},
			},
			Hints: []database.Hint{
				{ID: 206, RiddleID: 169, Text: "Think about what happen when something comes ti contact with water."},
			},
		},
		{
			ID:          170,
			Question:    "What gets shorter as it grows older?",
			Answer:      "A candle.",
			Explanation: "As a candle burns, it becomes shorter over time.",
			Category:    "Logic",
			Difficulty:  "Hard",
			Points:      15,
			Choices: []database.Choice{
				{ID: 562, RiddleID: 170, Text: "A candle"},
				{ID: 563, RiddleID: 170, Text: "A person"},
				{ID: 564, RiddleID: 170, Text: "A clock"},
				{ID: 565, RiddleID: 170, Text: "A tree"},
			},
			Hints: []database.Hint{
				{ID: 207, RiddleID: 170, Text: "It burns."},
			},
		},
		{
			ID:          171,
			Question:    "What five-letter word becomes shorter when you add two letters to it?",
			Answer:      "Short.",
			Explanation: "The word 'short' becomes 'shorter' when you add 'er.'",
			Category:    "Word",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 566, RiddleID: 171, Text: "Short"},
				{ID: 567, RiddleID: 171, Text: "Long"},
				{ID: 568, RiddleID: 171, Text: "Tiny"},
				{ID: 569, RiddleID: 171, Text: "Small"},
			},
			Hints: []database.Hint{
				{ID: 208, RiddleID: 171, Text: "It is related to size."},
			},
		},
		{
			ID:          172,
			Question:    "What is always found on the ground but never gets dirty?",
			Answer:      "Your shadow.",
			Explanation: "A shadow always appears on the ground but it never gets dirty.",
			Category:    "Logic",
			Difficulty:  "Hard",
			Points:      15,
			Choices: []database.Choice{
				{ID: 570, RiddleID: 172, Text: "Your shadow"},
				{ID: 571, RiddleID: 172, Text: "A rock"},
				{ID: 572, RiddleID: 172, Text: "A leaf"},
				{ID: 573, RiddleID: 172, Text: "A coin"},
			},
			Hints: []database.Hint{
				{ID: 209, RiddleID: 172, Text: "It is connected to light."},
			},
		},
		{
			ID:          173,
			Question:    "What has a head and a tail but no body?",
			Answer:      "A coin.",
			Explanation: "A coin has a head and a tail but no body.",
			Category:    "Logic",
			Difficulty:  "Hard",
			Points:      10,
			Choices: []database.Choice{
				{ID: 574, RiddleID: 173, Text: "A coin"},
				{ID: 575, RiddleID: 173, Text: "A snake"},
				{ID: 576, RiddleID: 173, Text: "A fish"},
				{ID: 577, RiddleID: 173, Text: "A lizard"},
			},
			Hints: []database.Hint{
				{ID: 210, RiddleID: 173, Text: "It’s a form of currency."},
			},
		},
		{
			ID:          174,
			Question:    "What has many teeth but cannot bite?",
			Answer:      "A comb.",
			Explanation: "A comb has many teeth but cannot bite.",
			Category:    "Word",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 578, RiddleID: 174, Text: "A comb"},
				{ID: 579, RiddleID: 174, Text: "A saw"},
				{ID: 580, RiddleID: 174, Text: "A zipper"},
				{ID: 581, RiddleID: 174, Text: "A rake"},
			},
			Hints: []database.Hint{
				{ID: 211, RiddleID: 174, Text: "It is used for grooming."},
			},
		},
		{
			ID:          175,
			Question:    "What has one head, one foot, and four legs?",
			Answer:      "A bed.",
			Explanation: "A bed has one head (headboard), one foot (footboard), and four legs (the supports).",
			Category:    "Logic",
			Difficulty:  "Hard",
			Points:      15,
			Choices: []database.Choice{
				{ID: 582, RiddleID: 175, Text: "A bed"},
				{ID: 583, RiddleID: 175, Text: "A chair"},
				{ID: 584, RiddleID: 175, Text: "A table"},
				{ID: 585, RiddleID: 175, Text: "A stool"},
			},
			Hints: []database.Hint{
				{ID: 212, RiddleID: 175, Text: "It’s furniture."},
			},
		},
		{
			ID:          176,
			Question:    "What gets smaller every time it takes a bath?",
			Answer:      "Soap.",
			Explanation: "Soap gets smaller as it is used during a bath.",
			Category:    "Logic",
			Difficulty:  "Easy",
			Points:      5,
			Choices: []database.Choice{
				{ID: 586, RiddleID: 176, Text: "Soap"},
				{ID: 587, RiddleID: 176, Text: "A towel"},
				{ID: 588, RiddleID: 176, Text: "A sponge"},
				{ID: 589, RiddleID: 176, Text: "A loofah"},
			},
			Hints: []database.Hint{
				{ID: 213, RiddleID: 176, Text: "It’s used for cleaning."},
			},
		},
		{
			ID:          177,
			Question:    "What 5-letter word typed in all capital letters can be read the same upside down?",
			Answer:      "SWIMS.",
			Explanation: "The word 'SWIMS' is the same upside down if typed in capital letters.",
			Category:    "Word",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 590, RiddleID: 177, Text: "SWIMS"},
				{ID: 591, RiddleID: 177, Text: "MOM"},
				{ID: 592, RiddleID: 177, Text: "WOW"},
				{ID: 593, RiddleID: 177, Text: "NOON"},
			},
			Hints: []database.Hint{
				{ID: 214, RiddleID: 177, Text: "It is a word related to water."},
			},
		},
		{
			ID:          178,
			Question:    "What do you bury when it's alive and dig up when it's dead?",
			Answer:      "A plant.",
			Explanation: "You plant a seed (bury it alive) and dig it up when it’s fully grown (when it’s dead).",
			Category:    "Logic",
			Difficulty:  "Hard",
			Points:      15,
			Choices: []database.Choice{
				{ID: 594, RiddleID: 178, Text: "A plant"},
				{ID: 595, RiddleID: 178, Text: "A fish"},
				{ID: 596, RiddleID: 178, Text: "A tree"},
				{ID: 597, RiddleID: 178, Text: "A bone"},
			},
			Hints: []database.Hint{
				{ID: 215, RiddleID: 178, Text: "It is something living."},
			},
		},
		{
			ID:          179,
			Question:    "What is it that we bury and it comes back to life?",
			Answer:      "A seed.",
			Explanation: "A seed is buried in the ground and comes back to life when it grows into a plant.",
			Category:    "General",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 598, RiddleID: 179, Text: "A seed"},
				{ID: 599, RiddleID: 179, Text: "A fish"},
				{ID: 600, RiddleID: 179, Text: "A tree"},
				{ID: 601, RiddleID: 179, Text: "A rock"},
			},
			Hints: []database.Hint{
				{ID: 216, RiddleID: 179, Text: "It is connected to growth."},
			},
		},
		{
			ID:          180,
			Question:    "When I say, 'You are staggering my son,' which animals am I talking about?",
			Answer:      "Chameleon.",
			Explanation: "The phrase 'staggering my son' refers to a chameleon walk.",
			Category:    "Word",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 602, RiddleID: 180, Text: "Chameleom"},
				{ID: 603, RiddleID: 180, Text: "Tigers"},
				{ID: 604, RiddleID: 180, Text: "Elephants"},
				{ID: 605, RiddleID: 180, Text: "Bears"},
			},
			Hints: []database.Hint{
				{ID: 217, RiddleID: 180, Text: "Think how they walk."},
			},
		},
		{
			ID:          181,
			Question:    "What is taken before you can get it?",
			Answer:      "A picture.",
			Explanation: "You take a picture before you can get it printed or displayed.",
			Category:    "Logic",
			Difficulty:  "Easy",
			Points:      5,
			Choices: []database.Choice{
				{ID: 606, RiddleID: 181, Text: "A picture"},
				{ID: 607, RiddleID: 181, Text: "A paper"},
				{ID: 608, RiddleID: 181, Text: "A memory"},
				{ID: 609, RiddleID: 181, Text: "A dream"},
			},
			Hints: []database.Hint{
				{ID: 218, RiddleID: 181, Text: "It involves capturing something."},
			},
		},
		{
			ID:          182,
			Question:    "What belongs to you but is used by everyone you meet?",
			Answer:      "Your name.",
			Explanation: "Your name belongs to you, but everyone you meet uses it.",
			Category:    "Logic",
			Difficulty:  "Hard",
			Points:      15,
			Choices: []database.Choice{
				{ID: 610, RiddleID: 182, Text: "Your name"},
				{ID: 611, RiddleID: 182, Text: "Your clothes"},
				{ID: 612, RiddleID: 182, Text: "Your phone"},
				{ID: 613, RiddleID: 182, Text: "Your thoughts"},
			},
			Hints: []database.Hint{
				{ID: 219, RiddleID: 182, Text: "It’s something that identifies you."},
			},
		},
		{
			ID:          183,
			Question:    "What is lighter than a feather but impossible to hold for much more than a minute?",
			Answer:      "Your breath.",
			Explanation: "Your breath is lighter than a feather but cannot be held for much longer than a minute.",
			Category:    "Logic",
			Difficulty:  "Easy",
			Points:      5,
			Choices: []database.Choice{
				{ID: 614, RiddleID: 183, Text: "Your breath"},
				{ID: 615, RiddleID: 183, Text: "A thought"},
				{ID: 616, RiddleID: 183, Text: "A smile"},
				{ID: 617, RiddleID: 183, Text: "A shadow"},
			},
			Hints: []database.Hint{
				{ID: 220, RiddleID: 183, Text: "It is necessary for life."},
			},
		},
		{
			ID:          184,
			Question:    "A cowboy rides into town on Friday. He stays three days, then rides out of town on Friday. How?",
			Answer:      "His horse's name is Friday.",
			Explanation: "The cowboy’s horse is named Friday, so he rides into town on Friday and out on the same day.",
			Category:    "Word",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 618, RiddleID: 184, Text: "His horse's name is Friday"},
				{ID: 619, RiddleID: 184, Text: "He is a time traveler"},
				{ID: 620, RiddleID: 184, Text: "He rides on Friday every week"},
				{ID: 621, RiddleID: 184, Text: "He stays in town for three Fridays"},
			},
			Hints: []database.Hint{
				{ID: 221, RiddleID: 184, Text: "Think about the name of his horse."},
			},
		},
		{
			ID:          185,
			Question:    "If your uncle's sister is not your aunt, then who is she to you?",
			Answer:      "Your mother.",
			Explanation: "Your uncle's sister is your mother, as she is the sister of your uncle.",
			Category:    "Logic",
			Difficulty:  "Easy",
			Points:      5,
			Choices: []database.Choice{
				{ID: 622, RiddleID: 185, Text: "Your mother"},
				{ID: 623, RiddleID: 185, Text: "Your aunt"},
				{ID: 624, RiddleID: 185, Text: "Your sister"},
				{ID: 625, RiddleID: 185, Text: "Your grandmother"},
			},
			Hints: []database.Hint{
				{ID: 222, RiddleID: 185, Text: "It’s a family relationship."},
			},
		},
		{
			ID:          186,
			Question:    "Two people are born at the same moment, but they don't have the same birthdays. How?",
			Answer:      "They were born in different time zones.",
			Explanation: "People born at the same moment in different time zones may have different birthdays depending on the time difference.",
			Category:    "Logic",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 626, RiddleID: 186, Text: "They were born in different time zones"},
				{ID: 627, RiddleID: 186, Text: "They were born in different years"},
				{ID: 628, RiddleID: 186, Text: "They were born on different days"},
				{ID: 629, RiddleID: 186, Text: "They were twins but not identical"},
			},
			Hints: []database.Hint{
				{ID: 223, RiddleID: 186, Text: "Consider the impact of the Earth’s rotation."},
			},
		},
		{
			ID:          187,
			Question:    "The person who made it does not need it. The person who bought it does not want it. The person who needs it does not know it. What is it?",
			Answer:      "A coffin.",
			Explanation: "A coffin is made for someone who has passed away, purchased by others, and not needed by the deceased themselves.",
			Category:    "Logic",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 630, RiddleID: 187, Text: "A coffin"},
				{ID: 631, RiddleID: 187, Text: "A will"},
				{ID: 632, RiddleID: 187, Text: "A gravestone"},
				{ID: 633, RiddleID: 187, Text: "A tomb"},
			},
			Hints: []database.Hint{
				{ID: 224, RiddleID: 187, Text: "It is associated with death."},
			},
		},
		{
			ID:          188,
			Question:    "A man goes outside in the rain without an umbrella or hat but doesn't get a single hair on his head wet. How?",
			Answer:      "He is bald.",
			Explanation: "The man has no hair on his head, so there is nothing to get wet.",
			Category:    "Logic",
			Difficulty:  "Easy",
			Points:      5,
			Choices: []database.Choice{
				{ID: 634, RiddleID: 188, Text: "He is bald"},
				{ID: 635, RiddleID: 188, Text: "He wears a raincoat"},
				{ID: 636, RiddleID: 188, Text: "He uses magic"},
				{ID: 637, RiddleID: 188, Text: "He stays under a roof"},
			},
			Hints: []database.Hint{
				{ID: 225, RiddleID: 188, Text: "Think about his physical appearance."},
			},
		},
		{
			ID:          189,
			Question:    "If you are running a race and pass the person in second, then what place are you in?",
			Answer:      "Second place.",
			Explanation: "If you pass the person in second, you take their place, which is second.",
			Category:    "Logic",
			Difficulty:  "Easy",
			Points:      5,
			Choices: []database.Choice{
				{ID: 638, RiddleID: 189, Text: "Second place"},
				{ID: 639, RiddleID: 189, Text: "First place"},
				{ID: 640, RiddleID: 189, Text: "Third place"},
				{ID: 641, RiddleID: 189, Text: "Last place"},
			},
			Hints: []database.Hint{
				{ID: 226, RiddleID: 189, Text: "You don't overtake the person in first."},
			},
		},
		{
			ID:          190,
			Question:    "You enter a room that contains a match, kerosene lamp, candle, and fireplace. What should you light first?",
			Answer:      "The match.",
			Explanation: "You need to light the match first to use it for lighting other things.",
			Category:    "Logic",
			Difficulty:  "Easy",
			Points:      5,
			Choices: []database.Choice{
				{ID: 642, RiddleID: 190, Text: "The match"},
				{ID: 643, RiddleID: 190, Text: "The candle"},
				{ID: 644, RiddleID: 190, Text: "The kerosene lamp"},
				{ID: 645, RiddleID: 190, Text: "The fireplace"},
			},
			Hints: []database.Hint{
				{ID: 227, RiddleID: 190, Text: "What is required to light the other items?"},
			},
		},
		{
			ID:          191,
			Question:    "A mother and father have four daughters, and each daughter has one brother. How many people are in the family?",
			Answer:      "Seven.",
			Explanation: "There are four daughters, one brother, and two parents, making a total of seven.",
			Category:    "Logic",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 646, RiddleID: 191, Text: "Seven"},
				{ID: 647, RiddleID: 191, Text: "Six"},
				{ID: 648, RiddleID: 191, Text: "Eight"},
				{ID: 649, RiddleID: 191, Text: "Five"},
			},
			Hints: []database.Hint{
				{ID: 228, RiddleID: 191, Text: "Don’t forget to include the parents."},
			},
		},
		{
			ID:          192,
			Question:    "If the day before yesterday was the 23rd, then what will be the day after tomorrow?",
			Answer:      "The 27th.",
			Explanation: "If the day before yesterday was the 23rd, today is the 25th, so the day after tomorrow is the 27th.",
			Category:    "Logic",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 650, RiddleID: 192, Text: "The 27th"},
				{ID: 651, RiddleID: 192, Text: "The 26th"},
				{ID: 652, RiddleID: 192, Text: "The 25th"},
				{ID: 653, RiddleID: 192, Text: "The 24th"},
			},
			Hints: []database.Hint{
				{ID: 229, RiddleID: 192, Text: "Count the days relative to the 23rd."},
			},
		},
		{
			ID:          193,
			Question:    "What common English verb becomes its own past tense by rearranging its letters?",
			Answer:      "Eat.",
			Explanation: "The word 'eat' can be rearranged to form its past tense, 'ate.'",
			Category:    "Wordplay",
			Difficulty:  "Hard",
			Points:      15,
			Choices: []database.Choice{
				{ID: 654, RiddleID: 193, Text: "Eat"},
				{ID: 655, RiddleID: 193, Text: "Read"},
				{ID: 656, RiddleID: 193, Text: "Run"},
				{ID: 657, RiddleID: 193, Text: "Write"},
			},
			Hints: []database.Hint{
				{ID: 230, RiddleID: 193, Text: "Think of a short verb related to food."},
			},
		},
		{
			ID:          194,
			Question:    "A is B's father but B isn't A's son. How?",
			Answer:      "B is A's daughter.",
			Explanation: "B is not A's son but A's daughter, as A is B's father.",
			Category:    "Logic",
			Difficulty:  "Easy",
			Points:      5,
			Choices: []database.Choice{
				{ID: 658, RiddleID: 194, Text: "B is A's daughter"},
				{ID: 659, RiddleID: 194, Text: "B is A's brother"},
				{ID: 660, RiddleID: 194, Text: "B is A's uncle"},
				{ID: 661, RiddleID: 194, Text: "B is A's cousin"},
			},
			Hints: []database.Hint{
				{ID: 231, RiddleID: 194, Text: "B can be a daughter."},
			},
		},
		{
			ID:          195,
			Question:    "What is one thing that all people, regardless of their politics or religion, have to agree is between heaven and earth?",
			Answer:      "The word 'and.'",
			Explanation: "The word 'and' is literally between 'heaven' and 'earth.'",
			Category:    "Wordplay",
			Difficulty:  "Medium",
			Points:      10,
			Choices: []database.Choice{
				{ID: 662, RiddleID: 195, Text: "The word 'and'"},
				{ID: 663, RiddleID: 195, Text: "Air"},
				{ID: 664, RiddleID: 195, Text: "Clouds"},
				{ID: 665, RiddleID: 195, Text: "Atmosphere"},
			},
			Hints: []database.Hint{
				{ID: 232, RiddleID: 195, Text: "It's a linguistic answer."},
			},
		},
	}
	fmt.Println(len(riddles))
	for i := 0; i < len(riddles); i++ {
		err := db.Create(&riddles[i]).Error
		if err != nil {
			// Log the error and stop processing further
			fmt.Printf("Failed to create riddle at index %d: %v\n", i, err)
			break
		}
		time.Sleep(time.Second * 5)
	}

}
